#!/usr/bin/env python3
"""
Analyze JDS (Just Dance Scores) correlation with motion metrics from CSV files.

This script:
1. Discovers and loads all alignment_results.csv files generated by batch_compare_all.py
2. Merges CSV data with JDS scores from jds_scores.py
3. Generates per-song scatter plots showing:
   - DTW (Dynamic Time Warping) vs JDS
   - PA-MPJPE (Procrustes Aligned Mean Per Joint Position Error) vs JDS
   - Both for Hand and Arm JDS categories
4. Computes correlation statistics (Pearson r and p-values)

Output:
- Per-song plots saved to: plots/per_song/
- Summary statistics printed to console

Usage:
    python3 scripts/evaluate/analyze_jds_from_files.py
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import pathlib
from glob import glob
import os
import sys

# Add parent directory to path
HERE = pathlib.Path(__file__).parent
sys.path.append(str(HERE / ".." / ".."))

# === DATASET (from your sheet) ===
from scripts.evaluate.data.jds_scores import data as jds_scores

# === Configuration ===
DEFAULT_HUMAN_RECORDINGS_GVHMR_BASE = pathlib.Path("/home/jkim3662/Videos/Switch4EAI/HumanRecordings_GVHMR/raw")

# Person name mapping from directory to JDS scores
PERSON_NAME_MAPPING = {
    # Directories that match JDS keys map to themselves (in order from jds_scores.py)
    "WT": "WT",
    "MG": "MG",
    "Ross": "Ross",
    "Nitish": "Nitish",
    "Daesol": "Daesol",
    "Rishi": "Rishi",
    "CH": "CH",
    "KY": "KY",
    "Mili": "Mili",
    "JH": "JH",
    # Backwards-compatible aliases (if any directory names differ)
    "Wontaek": "WT",
    "Morgan": "MG",
}

# Define color map for persons (match keys in jds_scores.py - all 10 people)
PERSON_COLORS = {
    'WT': '#1f77b4',      # blue
    'MG': '#ff7f0e',      # orange
    'Ross': '#2ca02c',    # green
    'Nitish': '#d62728',  # red
    'Daesol': '#9467bd',  # purple
    'Rishi': '#8c564b',   # brown
    'CH': '#e377c2',      # pink
    'KY': '#7f7f7f',      # gray
    'Mili': '#bcbd22',    # yellow-green
    'JH': '#17becf'       # cyan
}




def load_all_csv_files(base_dir):
    """
    Discover and load all alignment_results.csv files from the directory structure.
    
    Returns:
        DataFrame with columns: person, song, condition, pa_mpjpe, mpjpe, dtw, etc.
    """
    csv_files = glob(str(base_dir / "**" / "alignment_results.csv"), recursive=True)
    
    all_data = []
    
    for csv_file in csv_files:
        # Parse path to extract person, song, condition
        # Path structure: .../Person/Song/Song_Person_condition/alignment_results.csv
        path_parts = pathlib.Path(csv_file).parts
        
        # Find the person directory (should be a few levels up)
        try:
            # Get the parent directory name (e.g., "Old_Town_Road_WT_normal_1")
            recording_dir = pathlib.Path(csv_file).parent.name
            
            # Parse the recording directory name
            # Format: SongName_PersonName_condition
            parts = recording_dir.rsplit('_', 2)  # Split from right to get last 2 underscores
            if len(parts) >= 3:
                condition_type = parts[-2]  # e.g., "normal"
                condition_num = parts[-1]   # e.g., "1"
                condition = f"{condition_type}_{condition_num}"
                
                # Find person from path
                person_dir = pathlib.Path(csv_file).parent.parent.parent.name
                person = PERSON_NAME_MAPPING.get(person_dir, person_dir)
                
                # Find song from path
                song_dir = pathlib.Path(csv_file).parent.parent.name
                song = song_dir
                
                # Read CSV file
                df = pd.read_csv(csv_file)
                
                # Take only the last row (most recent run) if multiple rows exist
                # This handles cases where CSV was appended to multiple times
                if len(df) > 0:
                    row = df.iloc[-1]  # Take last row
                    
                    all_data.append({
                        'person': person,
                        'song': song,
                        'condition': condition,
                        'pa_mpjpe': row.get('pa_mpjpe', None),
                        'mpjpe': row.get('mpjpe', None),
                        'pa_mpjpe_dtw': row.get('pa_mpjpe_dtw', None),
                        'dtw_total_cost': row.get('dtw_total_cost', None),
                        'dtw_path_length': row.get('dtw_path_length', None),
                        'duration_sec': row.get('duration_sec', None),
                        'position_velocity_error_mean': row.get('position_velocity_error_mean', None),
                        'position_acceleration_error_mean': row.get('position_acceleration_error_mean', None),
                        'csv_path': csv_file
                    })
                    
                    if len(df) > 1:
                        print(f"Loaded: {person} / {song} / {condition} (used last of {len(df)} rows)")
                    else:
                        print(f"Loaded: {person} / {song} / {condition}")
        except Exception as e:
            print(f"Error parsing {csv_file}: {e}")
            continue
    
    return pd.DataFrame(all_data)

# Load all CSV data
print("Loading all CSV files...")
csv_data = load_all_csv_files(DEFAULT_HUMAN_RECORDINGS_GVHMR_BASE)
print(f"\nLoaded {len(csv_data)} records from CSV files")
print(f"Unique persons: {sorted(csv_data['person'].unique())}")
print(f"Unique songs: {sorted(csv_data['song'].unique())}")
print(f"Unique conditions: {sorted(csv_data['condition'].unique())}")


def merge_csv_with_jds(csv_df, jds_data):
    """
    Merge CSV data with JDS scores.
    
    Args:
        csv_df: DataFrame with CSV data (person, song, condition, metrics)
        jds_data: Dictionary with JDS scores from jds_scores.py
        
    Returns:
        DataFrame with merged data including JDS scores
    """
    merged_data = []
    
    for _, row in csv_df.iterrows():
        person = row['person']
        song = row['song']
        condition = row['condition']
        
        # Get JDS score for this combination
        jds_hand = None
        jds_arm = None
        
        if song in jds_data:
            if condition in jds_data[song]:
                jds_hand = jds_data[song][condition].get("Hand", {}).get(person)
                jds_arm = jds_data[song][condition].get("Arm", {}).get(person)
        
        # Add JDS scores to the row
        merged_data.append({
            **row.to_dict(),
            'jds_hand': jds_hand,
            'jds_arm': jds_arm
        })
    
    return pd.DataFrame(merged_data)

# Merge CSV data with JDS scores
print("\nMerging CSV data with JDS scores...")
merged_data = merge_csv_with_jds(csv_data, jds_scores)

# Filter out rows without JDS scores
merged_data_with_jds = merged_data[merged_data['jds_hand'].notna() | merged_data['jds_arm'].notna()].copy()
print(f"Records with JDS scores: {len(merged_data_with_jds)}")


def compute_dtw_per_second(row):
    """Compute DTW normalized by duration (DTW per second)"""
    if pd.notna(row['pa_mpjpe_dtw']) and pd.notna(row['duration_sec']) and row['duration_sec'] > 0:
        return row['pa_mpjpe_dtw']
    return None

# Add DTW per second metric (using PA-MPJPE-DTW directly as it's already per-frame average)
merged_data_with_jds['dtw'] = merged_data_with_jds.apply(compute_dtw_per_second, axis=1)


def plot_jds_vs_metric_per_song(
    merged_df,
    metric_column='pa_mpjpe',
    jds_column='jds_hand',
    include_run_types=None,
    include_persons=None,
    save_dir="plots",
    annotate=True
):
    """
    Create per-song scatter plots of JDS vs a metric (DTW or PA-MPJPE).
    
    Args:
        merged_df: DataFrame with merged CSV and JDS data
        metric_column: Column name for the metric (e.g., 'pa_mpjpe', 'dtw')
        jds_column: Column name for JDS scores ('jds_hand' or 'jds_arm')
        include_run_types: Set of condition types to include (e.g., {"normal", "upperbody"})
        include_persons: Set of persons to include (e.g., {"WT", "JH"})
        save_dir: Directory to save plots
        annotate: Whether to annotate data points
    """
    os.makedirs(save_dir, exist_ok=True)
    
    # Filter data
    df = merged_df.copy()
    
    # Filter by run types
    if include_run_types:
        df['run_type'] = df['condition'].str.split('_').str[0]
        df = df[df['run_type'].isin(include_run_types)]
    
    # Filter by persons
    if include_persons:
        df = df[df['person'].isin(include_persons)]
    
    # Filter out rows without the metric or JDS
    df = df[df[metric_column].notna() & df[jds_column].notna()]
    
    # Get unique songs
    songs = sorted(df['song'].unique())
    
    for song in songs:
        song_df = df[df['song'] == song]
        
        if len(song_df) < 2:
            print(f"[skip] Not enough data points for {song} / {metric_column}")
            continue
        
        # Extract data
        jds_values = song_df[jds_column].values
        metric_values = song_df[metric_column].values
        persons = song_df['person'].values
        labels = song_df.apply(lambda r: f"{r['condition']} ({r['person']})", axis=1).values
        
        # Compute correlation
        r, p = pearsonr(jds_values, metric_values)
        
        # Create plot
        plt.figure(figsize=(8, 6))
        
        # Plot each person with a different color
        for person in sorted(set(persons)):
            mask = persons == person
            color = PERSON_COLORS.get(person, '#7f7f7f')  # default gray if person not in map
            plt.scatter(jds_values[mask], metric_values[mask], 
                       s=50, alpha=0.7, color=color, label=None)
        
        # Regression line
        m, b = np.polyfit(jds_values, metric_values, 1)
        xs = np.linspace(min(jds_values), max(jds_values), 100)
        plt.plot(xs, m * xs + b, linestyle="--", alpha=0.8, color='black', 
                linewidth=1.5, label=f"r={r:.3f}, p={p:.4f}")
        
        # Annotations
        if annotate:
            for j, v, lbl in zip(jds_values, metric_values, labels):
                plt.annotate(lbl, (j, v), xytext=(5, 5), textcoords="offset points", 
                           fontsize=7, alpha=0.7)
        
        # Labels and title
        metric_name = metric_column.upper().replace('_', '-')
        jds_type = "Hand" if jds_column == 'jds_hand' else "Arm"
        
        title_parts = [song, f"JDS ({jds_type}) vs {metric_name}"]
        if include_run_types:
            title_parts.append(f"types={sorted(include_run_types)}")
        if include_persons:
            title_parts.append(f"persons={sorted(include_persons)}")
        
        plt.title(" | ".join(title_parts), fontsize=10)
        plt.xlabel(f"JDS ({jds_type})", fontsize=11)
        plt.ylabel(metric_name, fontsize=11)
        plt.legend(fontsize=9)
        plt.grid(True, linestyle="--", alpha=0.4)
        
        # Caption
        caption_text = (
            "r: Pearson correlation coefficient (−1 ≤ r ≤ 1)\n"
            "  • r > 0 → metric increases with JDS (positive correlation)\n"
            "  • r < 0 → metric decreases with JDS (negative correlation)\n"
            "p: two-tailed p-value testing H₀: r = 0\n"
            "  • p < 0.05 → statistically significant correlation"
        )
        plt.figtext(
            0.5, -0.05, caption_text,
            ha="center", va="top", fontsize=7, wrap=True
        )
        
        # Filename
        def safe(s): 
            return s.replace(' ', '_').replace('-', '').replace('(', '').replace(')', '')
        
        runpart = ""
        if include_run_types:
            runpart += "_types_" + "_".join(sorted(include_run_types))
        if include_persons:
            runpart += "_persons_" + "_".join(sorted(safe(p) for p in include_persons))
        
        filename = f"{safe(song)}_{safe(metric_name)}_vs_JDS{jds_type}{runpart}.png"
        filepath = os.path.join(save_dir, filename)
        
        plt.subplots_adjust(bottom=0.25)
        plt.savefig(filepath, bbox_inches="tight", dpi=150)
        plt.close()
        print(f"Saved: {filepath}")


def plot_hand_vs_arm_jds(
    merged_df,
    include_run_types=None,
    save_dir="plots",
    annotate=True,
    color_by='song'
):
    """
    Create a scatter plot comparing Hand JDS vs Arm JDS scores across all songs.
    
    Args:
        merged_df: DataFrame with merged CSV and JDS data
        include_run_types: Set of condition types to include (e.g., {"normal"})
        save_dir: Directory to save plots
        annotate: Whether to annotate data points
        color_by: 'song' or 'person' - what to color the points by
    """
    os.makedirs(save_dir, exist_ok=True)
    
    # Define color maps
    song_colors = {
        'Heart_Of_Glass': '#1f77b4',  # blue
        'Old_Town_Road': '#ff7f0e',   # orange
        'Padam_Padam': '#2ca02c',     # green
        'Pink_Venom': '#d62728',      # red
        'Unstoppable': '#9467bd',     # purple
    }
    
    # Filter data
    df = merged_df.copy()
    
    # Filter by run types
    if include_run_types:
        df['run_type'] = df['condition'].str.split('_').str[0]
        df = df[df['run_type'].isin(include_run_types)]
    
    # Filter out rows without both JDS scores
    df = df[df['jds_hand'].notna() & df['jds_arm'].notna()]
    
    if len(df) < 2:
        print("[skip] Not enough data points for Hand vs Arm JDS comparison")
        return
    
    # Extract data
    hand_values = df['jds_hand'].values
    arm_values = df['jds_arm'].values
    songs = df['song'].values
    persons = df['person'].values
    conditions = df['condition'].values
    labels = df.apply(lambda r: f"{r['song']}: {r['condition']} ({r['person']})", axis=1).values
    
    # Compute correlation
    r, p = pearsonr(hand_values, arm_values)
    
    # Create plot
    plt.figure(figsize=(10, 8))
    
    # Choose coloring scheme
    if color_by == 'song':
        color_map = song_colors
        categories = songs
        category_set = sorted(set(songs))
    else:  # color by person
        color_map = PERSON_COLORS
        categories = persons
        category_set = sorted(set(persons))
    
    # Plot each category with a different color
    for category in category_set:
        mask = categories == category
        color = color_map.get(category, '#7f7f7f')  # default gray if not in map
        plt.scatter(hand_values[mask], arm_values[mask], 
                   s=60, alpha=0.6, color=color, label=category)
    
    # y=x reference line
    min_val = min(min(hand_values), min(arm_values))
    max_val = max(max(hand_values), max(arm_values))
    plt.plot([min_val, max_val], [min_val, max_val], 
            linestyle=':', color='gray', linewidth=1.5, alpha=0.5, label='y=x')
    
    # Regression line
    m, b = np.polyfit(hand_values, arm_values, 1)
    xs = np.linspace(min(hand_values), max(hand_values), 100)
    plt.plot(xs, m * xs + b, linestyle="--", alpha=0.8, color='black', 
            linewidth=2, label=f"r={r:.3f}, p={p:.4f}")
    
    # Annotations
    if annotate:
        for h, a, lbl in zip(hand_values, arm_values, labels):
            plt.annotate(lbl, (h, a), xytext=(5, 5), textcoords="offset points", 
                       fontsize=6, alpha=0.6)
    
    # Labels and title
    color_desc = "by Song" if color_by == 'song' else "by Person"
    title_parts = [f"Hand JDS vs Arm JDS - All Songs ({color_desc})"]
    if include_run_types:
        title_parts.append(f"types={sorted(include_run_types)}")
    
    plt.title(" | ".join(title_parts), fontsize=12)
    plt.xlabel("Hand JDS Score", fontsize=11)
    plt.ylabel("Arm JDS Score", fontsize=11)
    plt.legend(fontsize=9, loc='best')
    plt.grid(True, linestyle="--", alpha=0.4)
    
    # Caption
    caption_text = (
        "r: Pearson correlation coefficient (−1 ≤ r ≤ 1)\n"
        "  • r > 0 → Arm score increases with Hand score (positive correlation)\n"
        "  • r < 0 → Arm score decreases with Hand score (negative correlation)\n"
        "p: two-tailed p-value testing H₀: r = 0\n"
        "  • p < 0.05 → statistically significant correlation"
    )
    plt.figtext(
        0.5, -0.05, caption_text,
        ha="center", va="top", fontsize=7, wrap=True
    )
    
    # Filename
    def safe(s): 
        return s.replace(' ', '_').replace('-', '').replace('(', '').replace(')', '')
    
    runpart = ""
    if include_run_types:
        runpart += "_types_" + "_".join(sorted(include_run_types))
    
    color_suffix = "_by_song" if color_by == 'song' else "_by_person"
    filename = f"Hand_vs_Arm_JDS_all_songs{color_suffix}{runpart}.png"
    filepath = os.path.join(save_dir, filename)
    
    plt.subplots_adjust(bottom=0.25)
    plt.savefig(filepath, bbox_inches="tight", dpi=150)
    plt.close()
    print(f"Saved: {filepath}")


def plot_metric_vs_jds_all_songs_subplots(
    merged_df,
    metric_column='dtw',
    jds_column='jds_hand',
    include_run_types={'normal'},
    save_dir="plots"
):
    """
    Plot metric (DTW, PA-MPJPE, MPJPE) vs JDS scores with all 5 songs as subplots in a single PNG.
    
    Args:
        merged_df: DataFrame with merged CSV and JDS data
        metric_column: Column name for the metric (e.g., 'dtw', 'pa_mpjpe', 'mpjpe')
        jds_column: Column for JDS scores ('jds_hand' or 'jds_arm')
        include_run_types: Set of run types to include (e.g., {'normal'})
        save_dir: Directory to save plots
    """
    os.makedirs(save_dir, exist_ok=True)
    
    # Filter data
    df = merged_df.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'].isin(include_run_types)]
    df = df[df[metric_column].notna() & df[jds_column].notna()]
    
    if len(df) < 2:
        print(f"[skip] Not enough data for {metric_column} vs {jds_column}")
        return
    
    # Song order by difficulty level
    song_order = ['Old_Town_Road', 'Heart_Of_Glass', 'Unstoppable', 'Padam_Padam', 'Pink_Venom']
    song_levels = {
        'Old_Town_Road': 'Lvl 1',
        'Heart_Of_Glass': 'Lvl 2',
        'Unstoppable': 'Lvl 2',
        'Padam_Padam': 'Lvl 3',
        'Pink_Venom': 'Lvl 4'
    }
    
    # Get unique songs and order by difficulty
    songs_in_data = set(df['song'].unique())
    songs = [s for s in song_order if s in songs_in_data]
    n_songs = len(songs)
    
    if n_songs == 0:
        print(f"[skip] No songs found for {metric_column} vs {jds_column}")
        return
    
    # Create subplots (1 row, n_songs columns)
    fig, axes = plt.subplots(1, n_songs, figsize=(5*n_songs, 5), sharey=False)
    if n_songs == 1:
        axes = [axes]
    
    # Format metric name for display
    if 'velocity' in metric_column:
        metric_name = 'MPJVE'  # Mean Per Joint Velocity Error
    elif 'acceleration' in metric_column:
        metric_name = 'MPJAE'  # Mean Per Joint Acceleration Error
    else:
        metric_name = metric_column.upper().replace('_', '-')
    jds_type = "Hand" if jds_column == 'jds_hand' else "Arm"
    
    for idx, (song, ax) in enumerate(zip(songs, axes)):
        song_df = df[df['song'] == song]
        
        if len(song_df) < 2:
            ax.text(0.5, 0.5, f'Insufficient data\n(n={len(song_df)})', 
                   ha='center', va='center', transform=ax.transAxes)
            ax.set_title(song.replace('_', ' '), fontsize=11, fontweight='bold')
            continue
        
        # Prepare data for this song
        jds_values = song_df[jds_column].values
        metric_values = song_df[metric_column].values
        persons = song_df['person'].values
        
        # Plot points colored by person
        for person in sorted(set(persons)):
            person_mask = persons == person
            color = PERSON_COLORS.get(person, '#7f7f7f')
            ax.scatter(jds_values[person_mask], metric_values[person_mask], 
                      s=60, alpha=0.6, color=color, edgecolors='black', linewidth=0.5)
        
        # Regression line
        if len(jds_values) >= 2:
            r, p = pearsonr(jds_values, metric_values)
            m, b = np.polyfit(jds_values, metric_values, 1)
            xs = np.linspace(min(jds_values), max(jds_values), 100)
            ax.plot(xs, m * xs + b, linestyle="--", alpha=0.8, color='black', linewidth=2)
            
            # Add correlation text
            sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""
            ax.text(0.05, 0.95, f"r={r:.3f}, p={p:.4f} {sig}", 
                   transform=ax.transAxes, fontsize=9, va='top',
                   bbox=dict(boxstyle='round', facecolor='white', alpha=0.7))
        
        # Labels
        ax.set_xlabel(f"JDS Score ({jds_type})", fontsize=10)
        if idx == 0:
            ax.set_ylabel(metric_name, fontsize=10)
        
        # Title with song name and level
        song_display = song.replace('_', ' ')
        song_level = song_levels.get(song, '')
        ax.set_title(f"{song_display}\n({song_level})", fontsize=11, fontweight='bold')
        ax.grid(True, linestyle="--", alpha=0.3)
    
    # Overall title
    runpart = f"types={sorted(include_run_types)}" if include_run_types else ""
    fig.suptitle(f"{metric_name} vs JDS ({jds_type}) - All Songs | {runpart}", 
                fontsize=13, fontweight='bold')
    
    # Legend for person colors
    from matplotlib.patches import Patch
    legend_elements = [Patch(facecolor=PERSON_COLORS[p], label=p, alpha=0.6, edgecolor='black') 
                      for p in sorted(PERSON_COLORS.keys()) if p in df['person'].values]
    fig.legend(handles=legend_elements, loc='upper right', 
              title='Person', fontsize=9, framealpha=0.9)
    
    # Filename
    def safe(s): 
        return s.replace(' ', '_').replace('-', '').replace('(', '').replace(')', '')
    
    runpart = ""
    if include_run_types:
        runpart += "_types_" + "_".join(sorted(include_run_types))
    
    filename = f"{safe(metric_name)}_vs_JDS{jds_type}_all_songs_subplots{runpart}.png"
    filepath = os.path.join(save_dir, filename)
    
    plt.tight_layout(rect=[0, 0, 0.98, 0.96])
    plt.savefig(filepath, bbox_inches="tight", dpi=150)
    plt.close()
    print(f"Saved: {filepath}")


def plot_jds_normal_vs_upperbody_all_songs(
    merged_df,
    jds_column='jds_hand',
    save_dir="plots"
):
    """
    Create a single figure with box plots comparing normal vs upperbody JDS scores for all songs.
    Individual points are colored by person.
    
    Args:
        merged_df: DataFrame with merged CSV and JDS data
        jds_column: 'jds_hand' or 'jds_arm'
        save_dir: Directory to save plots
    """
    os.makedirs(save_dir, exist_ok=True)
    
    # Person colors
    PERSON_COLORS = {
        'WT': '#1f77b4',  # blue
        'MG': '#ff7f0e',   # orange
        'Ross': '#2ca02c',     # green
        'Nitish': '#d62728',   # red
        'Daesol': '#9467bd',   # purple
        'JH': '#8c564b' # brown
    }
    
    # Filter data
    df = merged_df.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'].isin({'normal', 'upperbody'})]
    df = df[df[jds_column].notna()]
    
    # Song order by difficulty level
    song_order = ['Old_Town_Road', 'Heart_Of_Glass', 'Unstoppable', 'Padam_Padam', 'Pink_Venom']
    song_levels = {
        'Old_Town_Road': 'Lvl 1',
        'Heart_Of_Glass': 'Lvl 2',
        'Unstoppable': 'Lvl 2',
        'Padam_Padam': 'Lvl 3',
        'Pink_Venom': 'Lvl 4'
    }
    
    # Get songs in order
    songs_in_data = set(df['song'].unique())
    songs = [s for s in song_order if s in songs_in_data]
    n_songs = len(songs)
    
    if n_songs == 0:
        print(f"[skip] No data for JDS comparison")
        return
    
    # Create figure with subplots for each song
    fig, axes = plt.subplots(1, n_songs, figsize=(4*n_songs, 6), sharey=True)
    if n_songs == 1:
        axes = [axes]
    
    jds_type = "Hand" if jds_column == 'jds_hand' else "Arm"
    
    for idx, (song, ax) in enumerate(zip(songs, axes)):
        song_df = df[df['song'] == song]
        
        # Check if we have both conditions
        run_types_available = set(song_df['run_type'].unique())
        if len(run_types_available) < 2:
            ax.text(0.5, 0.5, f'Insufficient data\n(only {run_types_available})', 
                   ha='center', va='center', transform=ax.transAxes)
            ax.set_title(song.replace('_', ' '), fontsize=10)
            continue
        
        # Prepare data
        normal_data = song_df[song_df['run_type'] == 'normal']
        upperbody_data = song_df[song_df['run_type'] == 'upperbody']
        
        normal_vals = normal_data[jds_column].values
        upperbody_vals = upperbody_data[jds_column].values
        
        # Box plot (without filling)
        bp = ax.boxplot([normal_vals, upperbody_vals], 
                        labels=['Normal', 'Upperbody'],
                        widths=0.5,
                        patch_artist=False,
                        showfliers=False,  # Don't show outliers as we'll plot all points
                        medianprops=dict(color='black', linewidth=2),
                        boxprops=dict(color='black', linewidth=1.5),
                        whiskerprops=dict(color='black', linewidth=1.5),
                        capprops=dict(color='black', linewidth=1.5))
        
        # Plot individual points colored by person
        for i, data in enumerate([normal_data, upperbody_data], 1):
            for _, row in data.iterrows():
                person = row['person']
                jds_val = row[jds_column]
                color = PERSON_COLORS.get(person, '#7f7f7f')
                x = i + np.random.normal(0, 0.05)  # Jitter
                ax.scatter(x, jds_val, alpha=0.6, s=50, color=color, 
                          edgecolors='black', linewidth=0.5, zorder=3)
        
        # Statistical test
        from scipy.stats import mannwhitneyu
        if len(normal_vals) > 0 and len(upperbody_vals) > 0:
            statistic, p_value = mannwhitneyu(normal_vals, upperbody_vals, alternative='two-sided')
            sig = "***" if p_value < 0.001 else "**" if p_value < 0.01 else "*" if p_value < 0.05 else "ns"
            
            # Add significance annotation
            y_max = max(max(normal_vals), max(upperbody_vals))
            y_min = min(min(normal_vals), min(upperbody_vals))
            y_range = y_max - y_min
            y_pos = y_max + 0.08 * y_range
            
            ax.plot([1, 2], [y_pos, y_pos], 'k-', linewidth=1)
            ax.text(1.5, y_pos + 0.02 * y_range, sig, 
                   ha='center', va='bottom', fontsize=11, fontweight='bold')
            ax.text(1.5, y_pos - 0.04 * y_range, f'p={p_value:.3f}', 
                   ha='center', va='top', fontsize=8)
        
        # Title and labels with song level
        song_display = song.replace('_', ' ')
        song_level = song_levels.get(song, '')
        ax.set_title(f"{song_display}\n({song_level})", fontsize=11, fontweight='bold')
        ax.grid(True, axis='y', linestyle='--', alpha=0.3, zorder=0)
        ax.set_xlabel('')
        
        # Sample sizes
        ax.text(1, ax.get_ylim()[0], f'n={len(normal_vals)}', 
               ha='center', va='top', fontsize=8)
        ax.text(2, ax.get_ylim()[0], f'n={len(upperbody_vals)}', 
               ha='center', va='top', fontsize=8)
        
        # Rotate x labels
        ax.tick_params(axis='x', rotation=45)
    
    # Common y-label
    axes[0].set_ylabel(f'Just Dance Score ({jds_type})', fontsize=12, fontweight='bold')
    
    # Overall title
    fig.suptitle(f'Normal vs Upperbody: JDS ({jds_type}) Comparison Across Songs', 
                fontsize=14, fontweight='bold', y=0.98)
    
    # Legend for person colors
    from matplotlib.patches import Patch
    legend_elements = [Patch(facecolor=PERSON_COLORS[p], label=p, alpha=0.6, edgecolor='black') 
                      for p in sorted(PERSON_COLORS.keys()) if p in df['person'].values]
    fig.legend(handles=legend_elements, loc='upper right', 
              title='Person', fontsize=9, framealpha=0.9)
    
    # Box plot explanation
    explanation = (
        "Box: Q1 to Q3 (middle 50%), line = median. IQR = Q3-Q1. "
        "Whiskers: extend to Q1-1.5×IQR and Q3+1.5×IQR or furthest data within range (asymmetric if skewed). "
        "Points = individual measurements (colored by person). "
        "Significance: *** p<0.001, ** p<0.01, * p<0.05, ns = not significant"
    )
    fig.text(0.5, -0.05, explanation, ha='center', va='top', fontsize=8, 
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.3))
    
    # Filename
    filename = f"JDS_{jds_type}_Normal_vs_Upperbody_all_songs.png"
    filepath = os.path.join(save_dir, filename)
    
    plt.tight_layout(rect=[0, 0.08, 1, 0.96])
    plt.savefig(filepath, bbox_inches="tight", dpi=150)
    plt.close()
    print(f"Saved: {filepath}")


# === Generate plots ===
print("\n" + "="*80)
print("GENERATING PLOTS")
print("="*80)

# DTW vs JDS (Hand) - per song
print("\n--- DTW vs JDS (Hand) - All songs ---")
plot_jds_vs_metric_per_song(
    merged_data_with_jds,
    metric_column='dtw',
    jds_column='jds_hand',
    include_run_types={'normal'},
    save_dir="plots/per_song"
)

# PA-MPJPE vs JDS (Hand) - per song
print("\n--- PA-MPJPE vs JDS (Hand) - All songs ---")
plot_jds_vs_metric_per_song(
    merged_data_with_jds,
    metric_column='pa_mpjpe',
    jds_column='jds_hand',
    include_run_types={'normal'},
    save_dir="plots/per_song"
)

# DTW vs JDS (Arm) - per song
print("\n--- DTW vs JDS (Arm) - All songs ---")
plot_jds_vs_metric_per_song(
    merged_data_with_jds,
    metric_column='dtw',
    jds_column='jds_arm',
    include_run_types={'normal'},
    save_dir="plots/per_song"
)

# PA-MPJPE vs JDS (Arm) - per song
print("\n--- PA-MPJPE vs JDS (Arm) - All songs ---")
plot_jds_vs_metric_per_song(
    merged_data_with_jds,
    metric_column='pa_mpjpe',
    jds_column='jds_arm',
    include_run_types={'normal'},
    save_dir="plots/per_song"
)

# Hand vs Arm JDS comparison - all songs combined (colored by song)
print("\n--- Hand JDS vs Arm JDS - All songs combined (colored by song) ---")
plot_hand_vs_arm_jds(
    merged_data_with_jds,
    include_run_types={'normal'},
    save_dir="plots",
    color_by='song'
)

# Hand vs Arm JDS comparison - all songs combined (colored by person)
print("\n--- Hand JDS vs Arm JDS - All songs combined (colored by person) ---")
plot_hand_vs_arm_jds(
    merged_data_with_jds,
    include_run_types={'normal'},
    save_dir="plots",
    color_by='person'
)

# Metric vs JDS comparison - all songs as subplots
print("\n--- Metric vs JDS - All songs as subplots ---")
for metric in ['dtw', 'pa_mpjpe', 'mpjpe', 'position_velocity_error_mean', 'position_acceleration_error_mean']:
    for jds_type in ['jds_hand', 'jds_arm']:
        jds_name = "Hand" if jds_type == 'jds_hand' else "Arm"
        metric_display = metric.upper().replace('_', '-')
        if 'velocity' in metric:
            metric_display = 'MPJVE'
        elif 'acceleration' in metric:
            metric_display = 'MPJAE'
        print(f"  Generating {metric_display} vs JDS ({jds_name}) subplots...")
        plot_metric_vs_jds_all_songs_subplots(
            merged_data_with_jds,
            metric_column=metric,
            jds_column=jds_type,
            include_run_types={'normal'},
            save_dir="plots"
        )

# JDS Normal vs Upperbody comparison - all songs in one figure
print("\n--- JDS Normal vs Upperbody - All songs in one figure ---")
plot_jds_normal_vs_upperbody_all_songs(
    merged_data_with_jds,
    jds_column='jds_hand',
    save_dir="plots"
)
plot_jds_normal_vs_upperbody_all_songs(
    merged_data_with_jds,
    jds_column='jds_arm',
    save_dir="plots"
)

print("\n" + "="*80)
print("DONE! All plots saved to plots/per_song/")
print("="*80)

# Print summary statistics
print("\n" + "="*80)
print("SUMMARY STATISTICS")
print("="*80)

# Calculate correlation statistics across all songs
for metric_col, jds_col, metric_name, jds_type in [
    ('dtw', 'jds_hand', 'DTW', 'Hand'),
    ('pa_mpjpe', 'jds_hand', 'PA-MPJPE', 'Hand'),
    ('dtw', 'jds_arm', 'DTW', 'Arm'),
    ('pa_mpjpe', 'jds_arm', 'PA-MPJPE', 'Arm'),
    ('position_velocity_error_mean', 'jds_hand', 'MPJVE', 'Hand'),
    ('position_velocity_error_mean', 'jds_arm', 'MPJVE', 'Arm'),
    ('position_acceleration_error_mean', 'jds_hand', 'MPJAE', 'Hand'),
    ('position_acceleration_error_mean', 'jds_arm', 'MPJAE', 'Arm')
]:
    df = merged_data_with_jds.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'].isin({'normal'})]
    df = df[df[metric_col].notna() & df[jds_col].notna()]
    
    songs = sorted(df['song'].unique())
    
    print(f"\n{metric_name} vs JDS ({jds_type}):")
    print("-" * 60)
    
    for song in songs:
        song_df = df[df['song'] == song]
        if len(song_df) >= 2:
            jds_values = song_df[jds_col].values
            metric_values = song_df[metric_col].values
            r, p = pearsonr(jds_values, metric_values)
            sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""
            print(f"  {song:20s}: r={r:7.3f}, p={p:7.4f} {sig:3s} (n={len(song_df):2d})")

print("\n" + "="*80)
print("Legend: *** p<0.001, ** p<0.01, * p<0.05")
print("="*80)
