#!/usr/bin/env python3
"""
Analyze JDS (Just Dance Scores) correlation with motion metrics from CSV files.

This script:
1. Discovers and loads all alignment_results.csv files generated by batch_compare_all.py
2. Merges CSV data with JDS scores from jds_scores.py
3. Generates per-song scatter plots showing:
   - DTW (Dynamic Time Warping) vs JDS
   - PA-MPJPE (Procrustes Aligned Mean Per Joint Position Error) vs JDS
   - Both for Hand and Arm JDS categories
4. Computes correlation statistics (Pearson r and p-values)

Output:
- Per-song plots saved to: plots/per_song/
- Summary statistics printed to console

Usage:
    python3 scripts/evaluate/analyze_jds_from_files.py
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import pathlib
from glob import glob
import os
import sys

# Add parent directory to path
HERE = pathlib.Path(__file__).parent
sys.path.append(str(HERE / ".." / ".."))

# === DATASET (from your sheet) ===
from scripts.evaluate.data.jds_scores import data as jds_scores

# === Configuration ===
DEFAULT_HUMAN_RECORDINGS_GVHMR_BASE = pathlib.Path("/home/jkim3662/Videos/Switch4EAI/HumanRecordings_GVHMR/raw")

# Person name mapping from directory to JDS scores
PERSON_NAME_MAPPING = {
    # Directories that match JDS keys map to themselves (in order from jds_scores.py)
    "WT": "WT",
    "MG": "MG",
    "Ross": "Ross",
    "Nitish": "Nitish",
    "Daesol": "Daesol",
    "Rishi": "Rishi",
    "CH": "CH",
    "KY": "KY",
    "Mili": "Mili",
    "JH": "JH",
    # Backwards-compatible aliases (if any directory names differ)
    "Wontaek": "WT",
    "Morgan": "MG",
}

# Define color map for persons (match keys in jds_scores.py - all 10 people)
PERSON_COLORS = {
    'WT': '#1f77b4',      # blue
    'MG': '#ff7f0e',      # orange
    'Ross': '#2ca02c',    # green
    'Nitish': '#d62728',  # red
    'Daesol': '#9467bd',  # purple
    'Rishi': '#8c564b',   # brown
    'CH': '#e377c2',      # pink
    'KY': '#7f7f7f',      # gray
    'Mili': '#bcbd22',    # yellow-green
    'JH': '#17becf'       # cyan
}




def load_all_csv_files(base_dir):
    """
    Discover and load all alignment_results.csv files from the directory structure.
    
    Returns:
        DataFrame with columns: person, song, condition, pa_mpjpe, mpjpe, dtw, etc.
    """
    csv_files = glob(str(base_dir / "**" / "alignment_results.csv"), recursive=True)
    
    all_data = []
    
    for csv_file in csv_files:
        # Parse path to extract person, song, condition
        # Path structure: .../Person/Song/Song_Person_condition/alignment_results.csv
        path_parts = pathlib.Path(csv_file).parts
        
        # Find the person directory (should be a few levels up)
        try:
            # Get the parent directory name (e.g., "Old_Town_Road_WT_normal_1")
            recording_dir = pathlib.Path(csv_file).parent.name
            
            # Parse the recording directory name
            # Format: SongName_PersonName_condition
            parts = recording_dir.rsplit('_', 2)  # Split from right to get last 2 underscores
            if len(parts) >= 3:
                condition_type = parts[-2]  # e.g., "normal"
                condition_num = parts[-1]   # e.g., "1"
                condition = f"{condition_type}_{condition_num}"
                
                # Find person from path
                person_dir = pathlib.Path(csv_file).parent.parent.parent.name
                person = PERSON_NAME_MAPPING.get(person_dir, person_dir)
                
                # Find song from path
                song_dir = pathlib.Path(csv_file).parent.parent.name
                song = song_dir
                
                # Read CSV file
                df = pd.read_csv(csv_file)
                
                # Take only the last row (most recent run) if multiple rows exist
                # This handles cases where CSV was appended to multiple times
                if len(df) > 0:
                    row = df.iloc[-1]  # Take last row
                    
                    all_data.append({
                        'person': person,
                        'song': song,
                        'condition': condition,
                        'pa_mpjpe': row.get('pa_mpjpe', None),
                        'mpjpe': row.get('mpjpe', None),
                        'pa_mpjpe_dtw': row.get('pa_mpjpe_dtw', None),
                        'dtw_total_cost': row.get('dtw_total_cost', None),
                        'dtw_path_length': row.get('dtw_path_length', None),
                        'duration_sec': row.get('duration_sec', None),
                        'position_velocity_error_mean': row.get('position_velocity_error_mean', None),
                        'position_acceleration_error_mean': row.get('position_acceleration_error_mean', None),
                        'csv_path': csv_file
                    })
                    
                    if len(df) > 1:
                        print(f"Loaded: {person} / {song} / {condition} (used last of {len(df)} rows)")
                    else:
                        print(f"Loaded: {person} / {song} / {condition}")
        except Exception as e:
            print(f"Error parsing {csv_file}: {e}")
            continue
    
    return pd.DataFrame(all_data)

# Load all CSV data
print("Loading all CSV files...")
csv_data = load_all_csv_files(DEFAULT_HUMAN_RECORDINGS_GVHMR_BASE)
print(f"\nLoaded {len(csv_data)} records from CSV files")
print(f"Unique persons: {sorted(csv_data['person'].unique())}")
print(f"Unique songs: {sorted(csv_data['song'].unique())}")
print(f"Unique conditions: {sorted(csv_data['condition'].unique())}")


def merge_csv_with_jds(csv_df, jds_data):
    """
    Merge CSV data with JDS scores.
    
    Args:
        csv_df: DataFrame with CSV data (person, song, condition, metrics)
        jds_data: Dictionary with JDS scores from jds_scores.py
        
    Returns:
        DataFrame with merged data including JDS scores
    """
    merged_data = []
    
    for _, row in csv_df.iterrows():
        person = row['person']
        song = row['song']
        condition = row['condition']
        
        # Get JDS score for this combination
        jds_hand = None
        jds_arm = None
        
        if song in jds_data:
            if condition in jds_data[song]:
                jds_hand = jds_data[song][condition].get("Hand", {}).get(person)
                jds_arm = jds_data[song][condition].get("Arm", {}).get(person)
        
        # Add JDS scores to the row
        merged_data.append({
            **row.to_dict(),
            'jds_hand': jds_hand,
            'jds_arm': jds_arm
        })
    
    return pd.DataFrame(merged_data)

# Merge CSV data with JDS scores
print("\nMerging CSV data with JDS scores...")
merged_data = merge_csv_with_jds(csv_data, jds_scores)

# Filter out rows without JDS scores
merged_data_with_jds = merged_data[merged_data['jds_hand'].notna() | merged_data['jds_arm'].notna()].copy()
print(f"Records with JDS scores: {len(merged_data_with_jds)}")


def compute_dtw_per_second(row):
    """Compute DTW normalized by duration (DTW per second)"""
    if pd.notna(row['pa_mpjpe_dtw']) and pd.notna(row['duration_sec']) and row['duration_sec'] > 0:
        return row['pa_mpjpe_dtw']
    return None

# Add DTW per second metric (using PA-MPJPE-DTW directly as it's already per-frame average)
merged_data_with_jds['dtw'] = merged_data_with_jds.apply(compute_dtw_per_second, axis=1)


def plot_jds_vs_metric_per_song(
    merged_df,
    metric_column='pa_mpjpe',
    jds_column='jds_hand',
    include_run_types=None,
    include_persons=None,
    save_dir="plots",
    annotate=True
):
    """
    Create per-song scatter plots of JDS vs a metric (DTW or PA-MPJPE).
    
    Args:
        merged_df: DataFrame with merged CSV and JDS data
        metric_column: Column name for the metric (e.g., 'pa_mpjpe', 'dtw')
        jds_column: Column name for JDS scores ('jds_hand' or 'jds_arm')
        include_run_types: Set of condition types to include (e.g., {"normal", "upperbody"})
        include_persons: Set of persons to include (e.g., {"WT", "JH"})
        save_dir: Directory to save plots
        annotate: Whether to annotate data points
    """
    os.makedirs(save_dir, exist_ok=True)
    
    # Filter data
    df = merged_df.copy()
    
    # Filter by run types
    if include_run_types:
        df['run_type'] = df['condition'].str.split('_').str[0]
        df = df[df['run_type'].isin(include_run_types)]
    
    # Filter by persons
    if include_persons:
        df = df[df['person'].isin(include_persons)]
    
    # Filter out rows without the metric or JDS
    df = df[df[metric_column].notna() & df[jds_column].notna()]
    
    # Get unique songs
    songs = sorted(df['song'].unique())
    
    for song in songs:
        song_df = df[df['song'] == song]
        
        if len(song_df) < 2:
            print(f"[skip] Not enough data points for {song} / {metric_column}")
            continue
        
        # Extract data
        jds_values = song_df[jds_column].values
        metric_values = song_df[metric_column].values
        persons = song_df['person'].values
        labels = song_df.apply(lambda r: f"{r['condition']} ({r['person']})", axis=1).values
        
        # Compute correlation
        r, p = pearsonr(jds_values, metric_values)
        
        # Create plot
        plt.figure(figsize=(8, 6))
        
        # Plot each person with a different color
        for person in sorted(set(persons)):
            mask = persons == person
            color = PERSON_COLORS.get(person, '#7f7f7f')  # default gray if person not in map
            plt.scatter(jds_values[mask], metric_values[mask], 
                       s=50, alpha=0.7, color=color, label=None)
        
        # Regression line
        m, b = np.polyfit(jds_values, metric_values, 1)
        xs = np.linspace(min(jds_values), max(jds_values), 100)
        plt.plot(xs, m * xs + b, linestyle="--", alpha=0.8, color='black', 
                linewidth=1.5, label=f"r={r:.3f}, p={p:.4f}")
        
        # Annotations
        if annotate:
            for j, v, lbl in zip(jds_values, metric_values, labels):
                plt.annotate(lbl, (j, v), xytext=(5, 5), textcoords="offset points", 
                           fontsize=7, alpha=0.7)
        
        # Labels and title
        metric_name = metric_column.upper().replace('_', '-')
        jds_type = "Hand" if jds_column == 'jds_hand' else "Arm"
        
        title_parts = [song, f"JDS ({jds_type}) vs {metric_name}"]
        if include_run_types:
            title_parts.append(f"types={sorted(include_run_types)}")
        if include_persons:
            title_parts.append(f"persons={sorted(include_persons)}")
        
        plt.title(" | ".join(title_parts), fontsize=10)
        plt.xlabel(f"JDS ({jds_type})", fontsize=11)
        plt.ylabel(metric_name, fontsize=11)
        plt.legend(fontsize=9)
        plt.grid(True, linestyle="--", alpha=0.4)
        
        # Caption
        caption_text = (
            "r: Pearson correlation coefficient (−1 ≤ r ≤ 1)\n"
            "  • r > 0 → metric increases with JDS (positive correlation)\n"
            "  • r < 0 → metric decreases with JDS (negative correlation)\n"
            "p: two-tailed p-value testing H₀: r = 0\n"
            "  • p < 0.05 → statistically significant correlation"
        )
        plt.figtext(
            0.5, -0.05, caption_text,
            ha="center", va="top", fontsize=7, wrap=True
        )
        
        # Filename
        def safe(s): 
            return s.replace(' ', '_').replace('-', '').replace('(', '').replace(')', '')
        
        runpart = ""
        if include_run_types:
            runpart += "_types_" + "_".join(sorted(include_run_types))
        if include_persons:
            runpart += "_persons_" + "_".join(sorted(safe(p) for p in include_persons))
        
        filename = f"{safe(song)}_{safe(metric_name)}_vs_JDS{jds_type}{runpart}.png"
        filepath = os.path.join(save_dir, filename)
        
        plt.subplots_adjust(bottom=0.25)
        plt.savefig(filepath, bbox_inches="tight", dpi=150)
        plt.close()
        print(f"Saved: {filepath}")


def plot_hand_vs_arm_jds(
    merged_df,
    include_run_types=None,
    save_dir="plots",
    annotate=True,
    color_by='song'
):
    """
    Create a scatter plot comparing Hand JDS vs Arm JDS scores across all songs.
    
    Args:
        merged_df: DataFrame with merged CSV and JDS data
        include_run_types: Set of condition types to include (e.g., {"normal"})
        save_dir: Directory to save plots
        annotate: Whether to annotate data points
        color_by: 'song' or 'person' - what to color the points by
    """
    os.makedirs(save_dir, exist_ok=True)
    
    # Define color maps
    song_colors = {
        'Heart_Of_Glass': '#1f77b4',  # blue
        'Old_Town_Road': '#ff7f0e',   # orange
        'Padam_Padam': '#2ca02c',     # green
        'Pink_Venom': '#d62728',      # red
        'Unstoppable': '#9467bd',     # purple
    }
    
    # Filter data
    df = merged_df.copy()
    
    # Filter by run types
    if include_run_types:
        df['run_type'] = df['condition'].str.split('_').str[0]
        df = df[df['run_type'].isin(include_run_types)]
    
    # Filter out rows without both JDS scores
    df = df[df['jds_hand'].notna() & df['jds_arm'].notna()]
    
    if len(df) < 2:
        print("[skip] Not enough data points for Hand vs Arm JDS comparison")
        return
    
    # Extract data
    hand_values = df['jds_hand'].values
    arm_values = df['jds_arm'].values
    songs = df['song'].values
    persons = df['person'].values
    conditions = df['condition'].values
    labels = df.apply(lambda r: f"{r['song']}: {r['condition']} ({r['person']})", axis=1).values
    
    # Compute correlation
    r, p = pearsonr(hand_values, arm_values)
    
    # Create plot
    plt.figure(figsize=(10, 8))
    
    # Choose coloring scheme
    if color_by == 'song':
        color_map = song_colors
        categories = songs
        category_set = sorted(set(songs))
    else:  # color by person
        color_map = PERSON_COLORS
        categories = persons
        category_set = sorted(set(persons))
    
    # Plot each category with a different color
    for category in category_set:
        mask = categories == category
        color = color_map.get(category, '#7f7f7f')  # default gray if not in map
        plt.scatter(hand_values[mask], arm_values[mask], 
                   s=60, alpha=0.6, color=color, label=category)
    
    # y=x reference line
    min_val = min(min(hand_values), min(arm_values))
    max_val = max(max(hand_values), max(arm_values))
    plt.plot([min_val, max_val], [min_val, max_val], 
            linestyle=':', color='gray', linewidth=1.5, alpha=0.5, label='y=x')
    
    # Regression line
    m, b = np.polyfit(hand_values, arm_values, 1)
    xs = np.linspace(min(hand_values), max(hand_values), 100)
    plt.plot(xs, m * xs + b, linestyle="--", alpha=0.8, color='black', 
            linewidth=2, label=f"r={r:.3f}, p={p:.4f}")
    
    # Annotations
    if annotate:
        for h, a, lbl in zip(hand_values, arm_values, labels):
            plt.annotate(lbl, (h, a), xytext=(5, 5), textcoords="offset points", 
                       fontsize=6, alpha=0.6)
    
    # Labels and title
    color_desc = "by Song" if color_by == 'song' else "by Person"
    title_parts = [f"Hand JDS vs Arm JDS - All Songs ({color_desc})"]
    if include_run_types:
        title_parts.append(f"types={sorted(include_run_types)}")
    
    plt.title(" | ".join(title_parts), fontsize=12)
    plt.xlabel("Hand JDS Score", fontsize=11)
    plt.ylabel("Arm JDS Score", fontsize=11)
    plt.legend(fontsize=9, loc='best')
    plt.grid(True, linestyle="--", alpha=0.4)
    
    # Caption
    caption_text = (
        "r: Pearson correlation coefficient (−1 ≤ r ≤ 1)\n"
        "  • r > 0 → Arm score increases with Hand score (positive correlation)\n"
        "  • r < 0 → Arm score decreases with Hand score (negative correlation)\n"
        "p: two-tailed p-value testing H₀: r = 0\n"
        "  • p < 0.05 → statistically significant correlation"
    )
    plt.figtext(
        0.5, -0.05, caption_text,
        ha="center", va="top", fontsize=7, wrap=True
    )
    
    # Filename
    def safe(s): 
        return s.replace(' ', '_').replace('-', '').replace('(', '').replace(')', '')
    
    runpart = ""
    if include_run_types:
        runpart += "_types_" + "_".join(sorted(include_run_types))
    
    color_suffix = "_by_song" if color_by == 'song' else "_by_person"
    filename = f"Hand_vs_Arm_JDS_all_songs{color_suffix}{runpart}.png"
    filepath = os.path.join(save_dir, filename)
    
    plt.subplots_adjust(bottom=0.25)
    plt.savefig(filepath, bbox_inches="tight", dpi=150)
    plt.close()
    print(f"Saved: {filepath}")


def plot_metric_vs_jds_all_songs_subplots(
    merged_df,
    metric_column='dtw',
    jds_column='jds_hand',
    include_run_types={'normal'},
    save_dir="plots"
):
    """
    Plot metric (DTW, PA-MPJPE, MPJPE) vs JDS scores with all 5 songs as subplots in a single PNG.
    
    Args:
        merged_df: DataFrame with merged CSV and JDS data
        metric_column: Column name for the metric (e.g., 'dtw', 'pa_mpjpe', 'mpjpe')
        jds_column: Column for JDS scores ('jds_hand' or 'jds_arm')
        include_run_types: Set of run types to include (e.g., {'normal'})
        save_dir: Directory to save plots
    """
    os.makedirs(save_dir, exist_ok=True)
    
    # Filter data
    df = merged_df.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'].isin(include_run_types)]
    df = df[df[metric_column].notna() & df[jds_column].notna()]
    
    if len(df) < 2:
        print(f"[skip] Not enough data for {metric_column} vs {jds_column}")
        return
    
    # Song order by difficulty level
    song_order = ['Old_Town_Road', 'Heart_Of_Glass', 'Unstoppable', 'Padam_Padam', 'Pink_Venom']
    song_levels = {
        'Old_Town_Road': 'Lvl 1',
        'Heart_Of_Glass': 'Lvl 2',
        'Unstoppable': 'Lvl 2',
        'Padam_Padam': 'Lvl 3',
        'Pink_Venom': 'Lvl 4'
    }
    
    # Get unique songs and order by difficulty
    songs_in_data = set(df['song'].unique())
    songs = [s for s in song_order if s in songs_in_data]
    n_songs = len(songs)
    
    if n_songs == 0:
        print(f"[skip] No songs found for {metric_column} vs {jds_column}")
        return
    
    # Create subplots (1 row, n_songs columns)
    fig, axes = plt.subplots(1, n_songs, figsize=(5*n_songs, 5), sharey=False)
    if n_songs == 1:
        axes = [axes]
    
    # Format metric name for display
    if 'velocity' in metric_column:
        metric_name = 'MPJVE'  # Mean Per Joint Velocity Error
    elif 'acceleration' in metric_column:
        metric_name = 'MPJAE'  # Mean Per Joint Acceleration Error
    else:
        metric_name = metric_column.upper().replace('_', '-')
    jds_type = "Hand" if jds_column == 'jds_hand' else "Arm"
    
    for idx, (song, ax) in enumerate(zip(songs, axes)):
        song_df = df[df['song'] == song]
        
        if len(song_df) < 2:
            ax.text(0.5, 0.5, f'Insufficient data\n(n={len(song_df)})', 
                   ha='center', va='center', transform=ax.transAxes)
            ax.set_title(song.replace('_', ' '), fontsize=11, fontweight='bold')
            continue
        
        # Prepare data for this song
        jds_values = song_df[jds_column].values
        metric_values = song_df[metric_column].values
        persons = song_df['person'].values
        
        # Plot points colored by person
        for person in sorted(set(persons)):
            person_mask = persons == person
            color = PERSON_COLORS.get(person, '#7f7f7f')
            ax.scatter(jds_values[person_mask], metric_values[person_mask], 
                      s=60, alpha=0.6, color=color, edgecolors='black', linewidth=0.5)
        
        # Regression line
        if len(jds_values) >= 2:
            r, p = pearsonr(jds_values, metric_values)
            m, b = np.polyfit(jds_values, metric_values, 1)
            xs = np.linspace(min(jds_values), max(jds_values), 100)
            ax.plot(xs, m * xs + b, linestyle="--", alpha=0.8, color='black', linewidth=2)
            
            # Add correlation text
            sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""
            ax.text(0.05, 0.95, f"r={r:.3f}, p={p:.4f} {sig}", 
                   transform=ax.transAxes, fontsize=9, va='top',
                   bbox=dict(boxstyle='round', facecolor='white', alpha=0.7))
        
        # Labels
        ax.set_xlabel(f"JDS Score ({jds_type})", fontsize=10)
        if idx == 0:
            ax.set_ylabel(metric_name, fontsize=10)
        
        # Title with song name and level
        song_display = song.replace('_', ' ')
        song_level = song_levels.get(song, '')
        ax.set_title(f"{song_display}\n({song_level})", fontsize=11, fontweight='bold')
        ax.grid(True, linestyle="--", alpha=0.3)
    
    # Overall title
    runpart = f"types={sorted(include_run_types)}" if include_run_types else ""
    fig.suptitle(f"{metric_name} vs JDS ({jds_type}) - All Songs | {runpart}", 
                fontsize=13, fontweight='bold')
    
    # Legend for person colors
    from matplotlib.patches import Patch
    legend_elements = [Patch(facecolor=PERSON_COLORS[p], label=p, alpha=0.6, edgecolor='black') 
                      for p in sorted(PERSON_COLORS.keys()) if p in df['person'].values]
    fig.legend(handles=legend_elements, loc='upper right', 
              title='Person', fontsize=9, framealpha=0.9)
    
    # Filename
    def safe(s): 
        return s.replace(' ', '_').replace('-', '').replace('(', '').replace(')', '')
    
    runpart = ""
    if include_run_types:
        runpart += "_types_" + "_".join(sorted(include_run_types))
    
    filename = f"{safe(metric_name)}_vs_JDS{jds_type}_all_songs_subplots{runpart}.png"
    filepath = os.path.join(save_dir, filename)
    
    plt.tight_layout(rect=[0, 0, 0.98, 0.96])
    plt.savefig(filepath, bbox_inches="tight", dpi=150)
    plt.close()
    print(f"Saved: {filepath}")


def plot_jds_normal_vs_upperbody_all_songs(
    merged_df,
    jds_column='jds_hand',
    save_dir="plots"
):
    """
    Create a single figure with box plots comparing normal vs upperbody JDS scores for all songs.
    Individual points are colored by person.
    
    Args:
        merged_df: DataFrame with merged CSV and JDS data
        jds_column: 'jds_hand' or 'jds_arm'
        save_dir: Directory to save plots
    """
    os.makedirs(save_dir, exist_ok=True)
    
    # Person colors
    PERSON_COLORS = {
        'WT': '#1f77b4',  # blue
        'MG': '#ff7f0e',   # orange
        'Ross': '#2ca02c',     # green
        'Nitish': '#d62728',   # red
        'Daesol': '#9467bd',   # purple
        'JH': '#8c564b' # brown
    }
    
    # Filter data
    df = merged_df.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'].isin({'normal', 'upperbody'})]
    df = df[df[jds_column].notna()]
    
    # Song order by difficulty level
    song_order = ['Old_Town_Road', 'Heart_Of_Glass', 'Unstoppable', 'Padam_Padam', 'Pink_Venom']
    song_levels = {
        'Old_Town_Road': 'Lvl 1',
        'Heart_Of_Glass': 'Lvl 2',
        'Unstoppable': 'Lvl 2',
        'Padam_Padam': 'Lvl 3',
        'Pink_Venom': 'Lvl 4'
    }
    
    # Get songs in order
    songs_in_data = set(df['song'].unique())
    songs = [s for s in song_order if s in songs_in_data]
    n_songs = len(songs)
    
    if n_songs == 0:
        print(f"[skip] No data for JDS comparison")
        return
    
    # Create figure with subplots for each song
    fig, axes = plt.subplots(1, n_songs, figsize=(4*n_songs, 6), sharey=True)
    if n_songs == 1:
        axes = [axes]
    
    jds_type = "Hand" if jds_column == 'jds_hand' else "Arm"
    
    for idx, (song, ax) in enumerate(zip(songs, axes)):
        song_df = df[df['song'] == song]
        
        # Check if we have both conditions
        run_types_available = set(song_df['run_type'].unique())
        if len(run_types_available) < 2:
            ax.text(0.5, 0.5, f'Insufficient data\n(only {run_types_available})', 
                   ha='center', va='center', transform=ax.transAxes)
            ax.set_title(song.replace('_', ' '), fontsize=10)
            continue
        
        # Prepare data
        normal_data = song_df[song_df['run_type'] == 'normal']
        upperbody_data = song_df[song_df['run_type'] == 'upperbody']
        
        normal_vals = normal_data[jds_column].values
        upperbody_vals = upperbody_data[jds_column].values
        
        # Box plot (without filling)
        bp = ax.boxplot([normal_vals, upperbody_vals], 
                        labels=['Normal', 'Upperbody'],
                        widths=0.5,
                        patch_artist=False,
                        showfliers=False,  # Don't show outliers as we'll plot all points
                        medianprops=dict(color='black', linewidth=2),
                        boxprops=dict(color='black', linewidth=1.5),
                        whiskerprops=dict(color='black', linewidth=1.5),
                        capprops=dict(color='black', linewidth=1.5))
        
        # Plot individual points colored by person
        for i, data in enumerate([normal_data, upperbody_data], 1):
            for _, row in data.iterrows():
                person = row['person']
                jds_val = row[jds_column]
                color = PERSON_COLORS.get(person, '#7f7f7f')
                x = i + np.random.normal(0, 0.05)  # Jitter
                ax.scatter(x, jds_val, alpha=0.6, s=50, color=color, 
                          edgecolors='black', linewidth=0.5, zorder=3)
        
        # Statistical test
        from scipy.stats import mannwhitneyu
        if len(normal_vals) > 0 and len(upperbody_vals) > 0:
            statistic, p_value = mannwhitneyu(normal_vals, upperbody_vals, alternative='two-sided')
            sig = "***" if p_value < 0.001 else "**" if p_value < 0.01 else "*" if p_value < 0.05 else "ns"
            
            # Add significance annotation
            y_max = max(max(normal_vals), max(upperbody_vals))
            y_min = min(min(normal_vals), min(upperbody_vals))
            y_range = y_max - y_min
            y_pos = y_max + 0.08 * y_range
            
            ax.plot([1, 2], [y_pos, y_pos], 'k-', linewidth=1)
            ax.text(1.5, y_pos + 0.02 * y_range, sig, 
                   ha='center', va='bottom', fontsize=11, fontweight='bold')
            ax.text(1.5, y_pos - 0.04 * y_range, f'p={p_value:.3f}', 
                   ha='center', va='top', fontsize=8)
        
        # Title and labels with song level
        song_display = song.replace('_', ' ')
        song_level = song_levels.get(song, '')
        ax.set_title(f"{song_display}\n({song_level})", fontsize=11, fontweight='bold')
        ax.grid(True, axis='y', linestyle='--', alpha=0.3, zorder=0)
        ax.set_xlabel('')
        
        # Sample sizes
        ax.text(1, ax.get_ylim()[0], f'n={len(normal_vals)}', 
               ha='center', va='top', fontsize=8)
        ax.text(2, ax.get_ylim()[0], f'n={len(upperbody_vals)}', 
               ha='center', va='top', fontsize=8)
        
        # Rotate x labels
        ax.tick_params(axis='x', rotation=45)
    
    # Common y-label
    axes[0].set_ylabel(f'Just Dance Score ({jds_type})', fontsize=12, fontweight='bold')
    
    # Overall title
    fig.suptitle(f'Normal vs Upperbody: JDS ({jds_type}) Comparison Across Songs', 
                fontsize=14, fontweight='bold', y=0.98)
    
    # Legend for person colors
    from matplotlib.patches import Patch
    legend_elements = [Patch(facecolor=PERSON_COLORS[p], label=p, alpha=0.6, edgecolor='black') 
                      for p in sorted(PERSON_COLORS.keys()) if p in df['person'].values]
    fig.legend(handles=legend_elements, loc='upper right', 
              title='Person', fontsize=9, framealpha=0.9)
    
    # Box plot explanation
    explanation = (
        "Box: Q1 to Q3 (middle 50%), line = median. IQR = Q3-Q1. "
        "Whiskers: extend to Q1-1.5×IQR and Q3+1.5×IQR or furthest data within range (asymmetric if skewed). "
        "Points = individual measurements (colored by person). "
        "Significance: *** p<0.001, ** p<0.01, * p<0.05, ns = not significant"
    )
    fig.text(0.5, -0.05, explanation, ha='center', va='top', fontsize=8, 
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.3))
    
    # Filename
    filename = f"JDS_{jds_type}_Normal_vs_Upperbody_all_songs.png"
    filepath = os.path.join(save_dir, filename)
    
    plt.tight_layout(rect=[0, 0.08, 1, 0.96])
    plt.savefig(filepath, bbox_inches="tight", dpi=150)
    plt.close()
    print(f"Saved: {filepath}")


# === Generate plots ===
print("\n" + "="*80)
print("GENERATING PLOTS")
print("="*80)

# DTW vs JDS (Hand) - per song
print("\n--- DTW vs JDS (Hand) - All songs ---")
plot_jds_vs_metric_per_song(
    merged_data_with_jds,
    metric_column='dtw',
    jds_column='jds_hand',
    include_run_types={'normal'},
    save_dir="plots/per_song"
)

# PA-MPJPE vs JDS (Hand) - per song
print("\n--- PA-MPJPE vs JDS (Hand) - All songs ---")
plot_jds_vs_metric_per_song(
    merged_data_with_jds,
    metric_column='pa_mpjpe',
    jds_column='jds_hand',
    include_run_types={'normal'},
    save_dir="plots/per_song"
)

# DTW vs JDS (Arm) - per song
print("\n--- DTW vs JDS (Arm) - All songs ---")
plot_jds_vs_metric_per_song(
    merged_data_with_jds,
    metric_column='dtw',
    jds_column='jds_arm',
    include_run_types={'normal'},
    save_dir="plots/per_song"
)

# PA-MPJPE vs JDS (Arm) - per song
print("\n--- PA-MPJPE vs JDS (Arm) - All songs ---")
plot_jds_vs_metric_per_song(
    merged_data_with_jds,
    metric_column='pa_mpjpe',
    jds_column='jds_arm',
    include_run_types={'normal'},
    save_dir="plots/per_song"
)

# Hand vs Arm JDS comparison - all songs combined (colored by song)
print("\n--- Hand JDS vs Arm JDS - All songs combined (colored by song) ---")
plot_hand_vs_arm_jds(
    merged_data_with_jds,
    include_run_types={'normal'},
    save_dir="plots",
    color_by='song'
)

# Hand vs Arm JDS comparison - all songs combined (colored by person)
print("\n--- Hand JDS vs Arm JDS - All songs combined (colored by person) ---")
plot_hand_vs_arm_jds(
    merged_data_with_jds,
    include_run_types={'normal'},
    save_dir="plots",
    color_by='person'
)

# Metric vs JDS comparison - all songs as subplots
print("\n--- Metric vs JDS - All songs as subplots ---")
for metric in ['dtw', 'pa_mpjpe', 'mpjpe', 'position_velocity_error_mean', 'position_acceleration_error_mean']:
    for jds_type in ['jds_hand', 'jds_arm']:
        jds_name = "Hand" if jds_type == 'jds_hand' else "Arm"
        metric_display = metric.upper().replace('_', '-')
        if 'velocity' in metric:
            metric_display = 'MPJVE'
        elif 'acceleration' in metric:
            metric_display = 'MPJAE'
        print(f"  Generating {metric_display} vs JDS ({jds_name}) subplots...")
        plot_metric_vs_jds_all_songs_subplots(
            merged_data_with_jds,
            metric_column=metric,
            jds_column=jds_type,
            include_run_types={'normal'},
            save_dir="plots"
        )

# JDS Normal vs Upperbody comparison - all songs in one figure
print("\n--- JDS Normal vs Upperbody - All songs in one figure ---")
plot_jds_normal_vs_upperbody_all_songs(
    merged_data_with_jds,
    jds_column='jds_hand',
    save_dir="plots"
)
plot_jds_normal_vs_upperbody_all_songs(
    merged_data_with_jds,
    jds_column='jds_arm',
    save_dir="plots"
)

print("\n" + "="*80)
print("DONE! All plots saved to plots/per_song/")
print("="*80)

# Print summary statistics
print("\n" + "="*80)
print("SUMMARY STATISTICS")
print("="*80)

# Calculate correlation statistics across all songs
for metric_col, jds_col, metric_name, jds_type in [
    ('dtw', 'jds_hand', 'DTW', 'Hand'),
    ('pa_mpjpe', 'jds_hand', 'PA-MPJPE', 'Hand'),
    ('dtw', 'jds_arm', 'DTW', 'Arm'),
    ('pa_mpjpe', 'jds_arm', 'PA-MPJPE', 'Arm'),
    ('position_velocity_error_mean', 'jds_hand', 'MPJVE', 'Hand'),
    ('position_velocity_error_mean', 'jds_arm', 'MPJVE', 'Arm'),
    ('position_acceleration_error_mean', 'jds_hand', 'MPJAE', 'Hand'),
    ('position_acceleration_error_mean', 'jds_arm', 'MPJAE', 'Arm')
]:
    df = merged_data_with_jds.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'].isin({'normal'})]
    df = df[df[metric_col].notna() & df[jds_col].notna()]
    
    songs = sorted(df['song'].unique())
    
    print(f"\n{metric_name} vs JDS ({jds_type}):")
    print("-" * 60)
    
    for song in songs:
        song_df = df[df['song'] == song]
        if len(song_df) >= 2:
            jds_values = song_df[jds_col].values
            metric_values = song_df[metric_col].values
            r, p = pearsonr(jds_values, metric_values)
            sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""
            print(f"  {song:20s}: r={r:7.3f}, p={p:7.4f} {sig:3s} (n={len(song_df):2d})")

print("\n" + "="*80)
print("Legend: *** p<0.001, ** p<0.01, * p<0.05")
print("="*80)


# ============================================================================
# PAPER RESULTS GENERATION
# ============================================================================
print("\n" + "="*80)
print("PAPER RESULTS GENERATION")
print("="*80)

import seaborn as sns
import pingouin as pg
from scipy.stats import ttest_rel, wilcoxon
from scipy.stats import shapiro

# Set seaborn style for all paper plots
sns.set_theme(style="whitegrid", font_scale=1.1)

# Define difficulty levels for songs
SONG_DIFFICULTY = {
    'Old_Town_Road': 1,
    'Heart_Of_Glass': 2,
    'Unstoppable': 2,
    'Padam_Padam': 3,
    'Pink_Venom': 4
}

# Helper function to format song names with level
def format_song_with_level(song_name, multiline=False):
    """Format song name with level information."""
    song_display = song_name.replace('_', ' ')
    level = SONG_DIFFICULTY.get(song_name, None)
    if level:
        if multiline:
            return f"{song_display}\n(Lvl {level})"
        else:
            return f"{song_display} (Lvl {level})"
    return song_display

# ────────────────────────────────────────────────────────────────────────────
# 1. RELIABILITY
# ────────────────────────────────────────────────────────────────────────────
print("\n" + "-"*80)
print("1. RELIABILITY ANALYSIS")
print("-"*80)

def calculate_reliability():
    """Calculate test-retest reliability using ICC and CV."""
    
    # Filter to normal runs only (exclude upperbody)
    df = merged_data_with_jds.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'] == 'normal'].copy()
    
    reliability_results = []
    
    for song in sorted(df['song'].unique()):
        for jds_col, jds_name in [('jds_hand', 'Hand'), ('jds_arm', 'Arm')]:
            song_df = df[df['song'] == song]
            song_df = song_df[song_df[jds_col].notna()]
            
            if len(song_df) < 3:  # Need at least 3 observations for ICC
                continue
            
            # Prepare data for ICC: targets (persons), raters (repeats)
            # We need to pivot data: rows=persons, columns=repeats
            song_df = song_df.copy()
            song_df['repeat_num'] = song_df.groupby('person').cumcount() + 1
            
            # Create pivot table
            pivot_df = song_df.pivot_table(
                index='person',
                columns='repeat_num',
                values=jds_col,
                aggfunc='first'
            )
            
            # Need at least 2 repeats per person for ICC
            if pivot_df.shape[1] < 2:
                continue
            
            # Reshape for pingouin (needs long format: targets, raters, ratings)
            icc_data = []
            for person in pivot_df.index:
                for repeat in pivot_df.columns:
                    if pd.notna(pivot_df.loc[person, repeat]):
                        icc_data.append({
                            'targets': person,
                            'raters': f'repeat_{repeat}',
                            'ratings': pivot_df.loc[person, repeat]
                        })
            
            if len(icc_data) < 6:  # Need sufficient data points
                continue
            
            icc_df = pd.DataFrame(icc_data)
            
            # Calculate ICC(3,1) and ICC(3,k)
            try:
                icc_results = pg.intraclass_corr(
                    data=icc_df,
                    targets='targets',
                    raters='raters',
                    ratings='ratings'
                )
                
                # Extract ICC(3,1) - two-way mixed, single measures, consistency
                icc3_1_row = icc_results[icc_results['Type'] == 'ICC3']
                icc3_1 = icc3_1_row['ICC'].values[0] if len(icc3_1_row) > 0 else np.nan
                
                # Extract ICC(3,k) - two-way mixed, average measures, consistency
                icc3_k_row = icc_results[icc_results['Type'] == 'ICC3k']
                icc3_k = icc3_k_row['ICC'].values[0] if len(icc3_k_row) > 0 else np.nan
                
            except Exception as e:
                print(f"  Warning: ICC calculation failed for {song} / {jds_name}: {e}")
                icc3_1 = np.nan
                icc3_k = np.nan
            
            # Calculate Coefficient of Variation per person, then average
            cv_values = []
            for person in song_df['person'].unique():
                person_scores = song_df[song_df['person'] == person][jds_col].values
                if len(person_scores) >= 2:
                    mean_score = np.mean(person_scores)
                    std_score = np.std(person_scores, ddof=1)
                    if mean_score > 0:
                        cv = (std_score / mean_score) * 100
                        cv_values.append(cv)
            
            mean_cv = np.mean(cv_values) if len(cv_values) > 0 else np.nan
            
            n_subjects = len(song_df['person'].unique())
            
            reliability_results.append({
                'Song': format_song_with_level(song),
                'JDS_Type': jds_name,
                'ICC(3,1)': icc3_1,
                'ICC(3,k)': icc3_k,
                'CV(%)': mean_cv,
                'n_subjects': n_subjects
            })
    
    return pd.DataFrame(reliability_results)

# Calculate reliability
reliability_df = calculate_reliability()

# Sort by song order and filter for Hand JDS only
song_order = ['Old Town Road (Lvl 1)', 'Heart Of Glass (Lvl 2)', 'Unstoppable (Lvl 2)', 
              'Padam Padam (Lvl 3)', 'Pink Venom (Lvl 4)']
reliability_df['song_order'] = reliability_df['Song'].map({s: i for i, s in enumerate(song_order)})
reliability_df = reliability_df.sort_values(['song_order', 'JDS_Type']).drop('song_order', axis=1)

# Filter for Hand JDS only and remove JDS_Type column
reliability_df_hand = reliability_df[reliability_df['JDS_Type'] == 'Hand'].copy()
reliability_df_hand = reliability_df_hand.drop('JDS_Type', axis=1)

# Remove n_subjects column for paper table (can be mentioned in text)
reliability_df_paper = reliability_df_hand.drop('n_subjects', axis=1)

print("\nReliability Results (Hand JDS only):")
print(reliability_df_paper.to_string(index=False))

# Save reliability table
reliability_df_paper.to_csv('plots/reliability_table.csv', index=False)
print("\nSaved: plots/reliability_table.csv")

# Save as LaTeX with proper formatting for CVPR 2-column
# Rename columns to remove underscores
reliability_df_latex = reliability_df_paper.copy()
reliability_df_latex.columns = ['Song', 'ICC(3,1)', 'ICC(3,k)', 'CV (%)']

with open('plots/reliability_table.tex', 'w') as f:
    latex_str = reliability_df_latex.to_latex(
        index=False,
        float_format="%.2f",
        caption="Test-retest reliability of Hand JDS (n=10 subjects, 3 trials each).",
        label="tab:reliability",
        column_format='l|ccc',
        escape=False
    )
    f.write(latex_str)
print("Saved: plots/reliability_table.tex")

# Plot ICC(3,1) per song
if len(reliability_df) > 0:
    fig, ax = plt.subplots(figsize=(8, 5))
    
    # Define song order
    song_order = ['Old Town Road (Lvl 1)', 'Heart Of Glass (Lvl 2)', 'Unstoppable (Lvl 2)', 
                  'Padam Padam (Lvl 3)', 'Pink Venom (Lvl 4)']
    
    # Filter to only songs in data and maintain order
    songs = [s for s in song_order if s in reliability_df['Song'].values]
    x = np.arange(len(songs))
    width = 0.35
    
    hand_icc = []
    arm_icc = []
    
    for song in songs:
        hand_row = reliability_df[(reliability_df['Song'] == song) & (reliability_df['JDS_Type'] == 'Hand')]
        arm_row = reliability_df[(reliability_df['Song'] == song) & (reliability_df['JDS_Type'] == 'Arm')]
        
        hand_icc.append(hand_row['ICC(3,1)'].values[0] if len(hand_row) > 0 else 0)
        arm_icc.append(arm_row['ICC(3,1)'].values[0] if len(arm_row) > 0 else 0)
    
    ax.bar(x - width/2, hand_icc, width, label='Hand JDS', alpha=0.8, color='skyblue', edgecolor='black')
    ax.bar(x + width/2, arm_icc, width, label='Arm JDS', alpha=0.8, color='salmon', edgecolor='black')
    
    # Reference lines for ICC quality
    ax.axhline(y=0.75, color='orange', linestyle='--', linewidth=1.5, label='Good (ICC=0.75)', alpha=0.7)
    ax.axhline(y=0.9, color='green', linestyle='--', linewidth=1.5, label='Excellent (ICC=0.90)', alpha=0.7)
    
    ax.set_xlabel('Song', fontsize=10, fontweight='bold')
    ax.set_ylabel('ICC(3,1)', fontsize=10, fontweight='bold')
    ax.set_title('Test-Retest Reliability: ICC(3,1) by Song', fontsize=11, fontweight='bold')
    ax.set_xticks(x)
    # Create multiline labels with smaller font
    song_labels = [s.replace(' (Lvl ', '\n(Lvl ') for s in songs]
    ax.set_xticklabels(song_labels, fontsize=7, ha='center')
    ax.legend(fontsize=8, loc='lower right')
    ax.set_ylim([0, 1.0])
    ax.grid(axis='y', alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('plots/reliability_icc_barplot.png', dpi=150, bbox_inches='tight')
    plt.close()
    print("Saved: plots/reliability_icc_barplot.png")


# ────────────────────────────────────────────────────────────────────────────
# 2. VALIDITY
# ────────────────────────────────────────────────────────────────────────────
print("\n" + "-"*80)
print("2. VALIDITY ANALYSIS")
print("-"*80)

def calculate_validity():
    """Calculate correlations between JDS and motion metrics."""
    
    # Filter to normal runs only
    df = merged_data_with_jds.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'] == 'normal'].copy()
    
    validity_results = []
    
    metrics = ['dtw', 'mpjpe', 'pa_mpjpe']
    metric_names = {'dtw': 'DTW', 'mpjpe': 'MPJPE', 'pa_mpjpe': 'PA-MPJPE'}
    
    for song in sorted(df['song'].unique()):
        for metric_col in metrics:
            for jds_col, jds_name in [('jds_hand', 'Hand'), ('jds_arm', 'Arm')]:
                song_df = df[df['song'] == song]
                song_df = song_df[song_df[metric_col].notna() & song_df[jds_col].notna()]
                
                if len(song_df) < 3:
                    continue
                
                jds_vals = song_df[jds_col].values
                metric_vals = song_df[metric_col].values
                
                r, p = pearsonr(jds_vals, metric_vals)
                
                validity_results.append({
                    'Song': format_song_with_level(song),
                    'Metric': metric_names[metric_col],
                    'JDS_Type': jds_name,
                    'r': r,
                    'p': p,
                    'n': len(song_df)
                })
    
    return pd.DataFrame(validity_results)

# Calculate validity
validity_df = calculate_validity()

# Sort by song and metric order
song_order = ['Old Town Road (Lvl 1)', 'Heart Of Glass (Lvl 2)', 'Unstoppable (Lvl 2)', 
              'Padam Padam (Lvl 3)', 'Pink Venom (Lvl 4)']
metric_order = ['DTW', 'MPJPE', 'PA-MPJPE']
validity_df['song_order'] = validity_df['Song'].map({s: i for i, s in enumerate(song_order)})
validity_df['metric_order'] = validity_df['Metric'].map({m: i for i, m in enumerate(metric_order)})
validity_df = validity_df.sort_values(['song_order', 'metric_order', 'JDS_Type']).drop(['song_order', 'metric_order'], axis=1)

# Filter for Hand JDS only and remove JDS_Type and n columns
validity_df_hand = validity_df[validity_df['JDS_Type'] == 'Hand'].copy()
validity_df_paper = validity_df_hand.drop(['JDS_Type', 'n'], axis=1)

print("\nValidity Results (Hand JDS only):")
print(validity_df_paper.to_string(index=False))

# Save validity table
validity_df_paper.to_csv('plots/validity_correlation_table.csv', index=False)
print("\nSaved: plots/validity_correlation_table.csv")

# Save as LaTeX with proper formatting for CVPR 2-column
# Column names are already clean (Song, Metric, r, p)
validity_df_latex = validity_df_paper.copy()
validity_df_latex.columns = ['Song', 'Metric', 'r', 'p-value']

with open('plots/validity_correlation_table.tex', 'w') as f:
    latex_str = validity_df_latex.to_latex(
        index=False,
        float_format="%.2f",
        caption="Pearson correlation between Hand JDS and motion metrics (n=30 trials per song).",
        label="tab:validity",
        column_format='ll|cc',
        escape=False
    )
    f.write(latex_str)
print("Saved: plots/validity_correlation_table.tex")

# Create heatmaps for each JDS type
for jds_name in ['Hand', 'Arm']:
    jds_validity = validity_df[validity_df['JDS_Type'] == jds_name]
    
    if len(jds_validity) == 0:
        continue
    
    # Pivot for heatmap: rows=metrics, columns=songs, values=r
    heatmap_data = jds_validity.pivot_table(
        index='Metric',
        columns='Song',
        values='r',
        aggfunc='first'
    )
    
    # Define song order and reindex columns
    song_order = ['Old Town Road (Lvl 1)', 'Heart Of Glass (Lvl 2)', 'Unstoppable (Lvl 2)', 
                  'Padam Padam (Lvl 3)', 'Pink Venom (Lvl 4)']
    existing_songs = [s for s in song_order if s in heatmap_data.columns]
    heatmap_data = heatmap_data[existing_songs]
    
    # Define metric order
    metric_order = ['DTW', 'MPJPE', 'PA-MPJPE']
    existing_metrics = [m for m in metric_order if m in heatmap_data.index]
    heatmap_data = heatmap_data.loc[existing_metrics]
    
    # Adjust figure size for 2-column format (narrower width, taller height)
    fig, ax = plt.subplots(figsize=(7, 4))
    
    # Rename columns to use multiline format
    heatmap_data.columns = [col.replace(' (Lvl ', '\n(Lvl ') for col in heatmap_data.columns]
    
    # Create heatmap with diverging colormap centered at 0
    sns.heatmap(
        heatmap_data,
        annot=True,
        fmt='.2f',
        cmap='RdBu_r',
        center=0,
        vmin=-1,
        vmax=1,
        cbar_kws={'label': 'Pearson r', 'shrink': 0.8},
        linewidths=0.5,
        linecolor='gray',
        ax=ax,
        annot_kws={'fontsize': 11, 'fontweight': 'bold'}
    )
    
    ax.set_title(f'Validity: Correlation between {jds_name} JDS and Motion Metrics',
                fontsize=12, fontweight='bold', pad=12)
    ax.set_xlabel('Song', fontsize=11, fontweight='bold')
    ax.set_ylabel('Metric', fontsize=11, fontweight='bold')
    ax.tick_params(axis='x', rotation=0, labelsize=9)
    ax.tick_params(axis='y', rotation=0, labelsize=10)
    
    plt.tight_layout()
    filename = f'plots/validity_heatmap_{jds_name.lower()}.png'
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved: {filename}")

# Create grouped bar plot showing average |r| per metric
if len(validity_df) > 0:
    # Calculate mean and std of |r| per metric and JDS type
    summary_data = validity_df.groupby(['Metric', 'JDS_Type']).agg({
        'r': lambda x: np.mean(np.abs(x))
    }).reset_index()
    summary_data.rename(columns={'r': 'mean_abs_r'}, inplace=True)
    
    # Calculate std of |r|
    std_data = validity_df.groupby(['Metric', 'JDS_Type']).agg({
        'r': lambda x: np.std(np.abs(x))
    }).reset_index()
    std_data.rename(columns={'r': 'std_abs_r'}, inplace=True)
    
    summary_data = summary_data.merge(std_data, on=['Metric', 'JDS_Type'])
    
    fig, ax = plt.subplots(figsize=(7, 5))
    
    # Define metric order
    metric_order = ['DTW', 'MPJPE', 'PA-MPJPE']
    metrics = [m for m in metric_order if m in summary_data['Metric'].values]
    x = np.arange(len(metrics))
    width = 0.35
    
    hand_data = summary_data[summary_data['JDS_Type'] == 'Hand']
    arm_data = summary_data[summary_data['JDS_Type'] == 'Arm']
    
    hand_means = [hand_data[hand_data['Metric'] == m]['mean_abs_r'].values[0] if len(hand_data[hand_data['Metric'] == m]) > 0 else 0 for m in metrics]
    hand_stds = [hand_data[hand_data['Metric'] == m]['std_abs_r'].values[0] if len(hand_data[hand_data['Metric'] == m]) > 0 else 0 for m in metrics]
    
    arm_means = [arm_data[arm_data['Metric'] == m]['mean_abs_r'].values[0] if len(arm_data[arm_data['Metric'] == m]) > 0 else 0 for m in metrics]
    arm_stds = [arm_data[arm_data['Metric'] == m]['std_abs_r'].values[0] if len(arm_data[arm_data['Metric'] == m]) > 0 else 0 for m in metrics]
    
    ax.bar(x - width/2, hand_means, width, yerr=hand_stds, label='Hand JDS',
          alpha=0.8, color='skyblue', edgecolor='black', capsize=5)
    ax.bar(x + width/2, arm_means, width, yerr=arm_stds, label='Arm JDS',
          alpha=0.8, color='salmon', edgecolor='black', capsize=5)
    
    ax.set_xlabel('Motion Metric', fontsize=11, fontweight='bold')
    ax.set_ylabel('Mean |r| (across songs)', fontsize=11, fontweight='bold')
    ax.set_title('Validity: Average Correlation Strength by Metric', fontsize=12, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(metrics, fontsize=10)
    ax.legend(fontsize=9, loc='upper right')
    ax.grid(axis='y', alpha=0.3)
    ax.set_ylim([0, 1.0])
    
    plt.tight_layout()
    plt.savefig('plots/validity_summary_barplot.png', dpi=150, bbox_inches='tight')
    plt.close()
    print("Saved: plots/validity_summary_barplot.png")

# Correlate mean JDS per song with difficulty level
print("\n--- JDS vs Song Difficulty ---")
df_normal = merged_data_with_jds.copy()
df_normal['run_type'] = df_normal['condition'].str.split('_').str[0]
df_normal = df_normal[df_normal['run_type'] == 'normal']

for jds_col, jds_name in [('jds_hand', 'Hand'), ('jds_arm', 'Arm')]:
    song_jds_means = []
    song_difficulties = []
    
    for song in sorted(df_normal['song'].unique()):
        if song in SONG_DIFFICULTY:
            song_df = df_normal[df_normal['song'] == song]
            song_df = song_df[song_df[jds_col].notna()]
            if len(song_df) > 0:
                mean_jds = song_df[jds_col].mean()
                song_jds_means.append(mean_jds)
                song_difficulties.append(SONG_DIFFICULTY[song])
    
    if len(song_jds_means) >= 3:
        r, p = pearsonr(song_difficulties, song_jds_means)
        print(f"  {jds_name} JDS vs Difficulty: r={r:.3f}, p={p:.4f}")


# ────────────────────────────────────────────────────────────────────────────
# 3. SENSITIVITY
# ────────────────────────────────────────────────────────────────────────────
print("\n" + "-"*80)
print("3. SENSITIVITY ANALYSIS")
print("-"*80)

def calculate_sensitivity():
    """Evaluate JDS sensitivity to degraded motion (upperbody vs normal)."""
    
    # Filter to normal and upperbody runs
    df = merged_data_with_jds.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'].isin({'normal', 'upperbody'})].copy()
    
    sensitivity_results = []
    
    for song in sorted(df['song'].unique()):
        for jds_col, jds_name in [('jds_hand', 'Hand'), ('jds_arm', 'Arm')]:
            song_df = df[df['song'] == song]
            
            normal_df = song_df[song_df['run_type'] == 'normal']
            upperbody_df = song_df[song_df['run_type'] == 'upperbody']
            
            normal_scores = normal_df[normal_df[jds_col].notna()][jds_col].values
            upperbody_scores = upperbody_df[upperbody_df[jds_col].notna()][jds_col].values
            
            if len(normal_scores) < 2 or len(upperbody_scores) < 2:
                continue
            
            mean_normal = np.mean(normal_scores)
            std_normal = np.std(normal_scores, ddof=1)
            mean_upperbody = np.mean(upperbody_scores)
            std_upperbody = np.std(upperbody_scores, ddof=1)
            delta = mean_normal - mean_upperbody
            
            # Check for paired data (same persons in both conditions)
            normal_persons = set(normal_df['person'].unique())
            upperbody_persons = set(upperbody_df['person'].unique())
            paired_persons = normal_persons & upperbody_persons
            
            if len(paired_persons) >= 3:
                # Paired test
                paired_normal = []
                paired_upperbody = []
                
                for person in paired_persons:
                    person_normal = normal_df[normal_df['person'] == person][jds_col].values
                    person_upperbody = upperbody_df[upperbody_df['person'] == person][jds_col].values
                    
                    if len(person_normal) > 0 and len(person_upperbody) > 0:
                        paired_normal.append(np.mean(person_normal))
                        paired_upperbody.append(np.mean(person_upperbody))
                
                paired_normal = np.array(paired_normal)
                paired_upperbody = np.array(paired_upperbody)
                
                # Test normality of differences
                differences = paired_normal - paired_upperbody
                if len(differences) >= 3:
                    _, p_normality = shapiro(differences)
                    
                    if p_normality > 0.05:
                        # Use paired t-test
                        _, p_value = ttest_rel(paired_normal, paired_upperbody)
                    else:
                        # Use Wilcoxon test
                        _, p_value = wilcoxon(paired_normal, paired_upperbody)
                else:
                    p_value = np.nan
                
                # Cohen's d for paired samples
                pooled_std = np.sqrt((std_normal**2 + std_upperbody**2) / 2)
                cohens_d = delta / pooled_std if pooled_std > 0 else np.nan
            else:
                # Unpaired comparison - report but don't do statistical test
                p_value = np.nan
                pooled_std = np.sqrt((std_normal**2 + std_upperbody**2) / 2)
                cohens_d = delta / pooled_std if pooled_std > 0 else np.nan
            
            sensitivity_results.append({
                'Song': format_song_with_level(song),
                'JDS_Type': jds_name,
                'Mean_Normal': mean_normal,
                'Mean_Upperbody': mean_upperbody,
                'Δ': delta,
                'p': p_value,
                'Effect_Size': cohens_d
            })
    
    return pd.DataFrame(sensitivity_results)

# Calculate sensitivity
sensitivity_df = calculate_sensitivity()

# Sort by song order
song_order = ['Old Town Road (Lvl 1)', 'Heart Of Glass (Lvl 2)', 'Unstoppable (Lvl 2)', 
              'Padam Padam (Lvl 3)', 'Pink Venom (Lvl 4)']
sensitivity_df['song_order'] = sensitivity_df['Song'].map({s: i for i, s in enumerate(song_order)})
sensitivity_df = sensitivity_df.sort_values(['song_order', 'JDS_Type']).drop('song_order', axis=1)

# Filter for Hand JDS only and remove JDS_Type column
sensitivity_df_hand = sensitivity_df[sensitivity_df['JDS_Type'] == 'Hand'].copy()
sensitivity_df_paper = sensitivity_df_hand.drop('JDS_Type', axis=1)

print("\nSensitivity Results (Hand JDS only):")
print(sensitivity_df_paper.to_string(index=False))

# Save sensitivity table
sensitivity_df_paper.to_csv('plots/sensitivity_table.csv', index=False)
print("\nSaved: plots/sensitivity_table.csv")

# Save as LaTeX with CVPR-style formatting matching bias table
sensitivity_df_latex = sensitivity_df_paper.copy()

# Convert to thousands
sensitivity_df_latex['Normal_k'] = sensitivity_df_latex['Mean_Normal'] / 1000
sensitivity_df_latex['Upperbody_k'] = sensitivity_df_latex['Mean_Upperbody'] / 1000
sensitivity_df_latex['Delta_k'] = sensitivity_df_latex['Δ'] / 1000

# Calculate total/overall statistics across all songs
df_sens_total = merged_data_with_jds.copy()
df_sens_total['run_type'] = df_sens_total['condition'].str.split('_').str[0]
df_sens_total = df_sens_total[df_sens_total['run_type'].isin({'normal', 'upperbody'})].copy()
df_sens_total = df_sens_total[df_sens_total['jds_hand'].notna()]

normal_scores = df_sens_total[df_sens_total['run_type'] == 'normal']['jds_hand'].values
upperbody_scores = df_sens_total[df_sens_total['run_type'] == 'upperbody']['jds_hand'].values

total_mean_normal = np.mean(normal_scores) / 1000
total_mean_upperbody = np.mean(upperbody_scores) / 1000
total_delta_k = total_mean_normal - total_mean_upperbody

# Test if total difference is significant
from scipy.stats import ttest_ind
_, total_p = ttest_ind(normal_scores, upperbody_scores)

# Total effect size (Cohen's d)
pooled_std = np.sqrt((np.std(normal_scores, ddof=1)**2 + np.std(upperbody_scores, ddof=1)**2) / 2)
total_effect_size = (np.mean(normal_scores) - np.mean(upperbody_scores)) / pooled_std if pooled_std > 0 else 0

# Build custom LaTeX table
with open('plots/sensitivity_table.tex', 'w') as f:
    f.write("\\begin{table}[t]\n")
    f.write("\\caption{Sensitivity of hand-mounted JDS to motion degradation (n=30 trials per song). ")
    f.write("Values denote mean Just Dance Scores (×10³). ")
    f.write("$\\Delta$ represents difference between normal and upperbody conditions.}\n")
    f.write("\\label{tab:sensitivity}\n")
    f.write("\\centering\n")
    f.write("\\resizebox{\\columnwidth}{!}{\n")
    f.write("\\begin{tabular}{l|cc|c|cc}\n")
    f.write("\\toprule\n")
    f.write(" & \\multicolumn{2}{c|}{\\textbf{Mean JDS (×10³)}} & \\textbf{Difference} & \\multicolumn{2}{c}{\\textbf{Statistics}} \\\\\n")
    f.write("\\cmidrule(lr){2-3} \\cmidrule(lr){5-6}\n")
    f.write("\\textbf{Song} & Normal & Upperbody & $\\Delta$ & p & Cohen's d \\\\\n")
    f.write("\\midrule\n")
    
    # Write data rows
    for _, row in sensitivity_df_latex.iterrows():
        song = row['Song']
        normal = row['Normal_k']
        upperbody = row['Upperbody_k']
        delta = row['Delta_k']
        p_val = row['p']
        effect = row['Effect_Size']
        
        # Format p-value with proper LaTeX < symbol
        if pd.notna(p_val):
            if p_val < 0.01:
                p_str = "$<$.01"
            else:
                p_str = f"{p_val:.2f}"
        else:
            p_str = "---"
        
        f.write(f"{song} & {normal:.1f} & {upperbody:.1f} & {delta:+.1f} & {p_str} & {effect:.2f} \\\\\n")
    
    # Write total summary row
    f.write("\\midrule\n")
    # Format total p-value
    if total_p < 0.01:
        total_p_str = "$<$.01"
    else:
        total_p_str = f"{total_p:.2f}"
    
    f.write(f"\\textbf{{Total}} & \\textbf{{{total_mean_normal:.1f}}} & \\textbf{{{total_mean_upperbody:.1f}}} & \\textbf{{{total_delta_k:+.1f}}} & \\textbf{{{total_p_str}}} & \\textbf{{{total_effect_size:.2f}}} \\\\\n")
    f.write("\\bottomrule\n")
    f.write("\\end{tabular}}\n")
    f.write("\\end{table}\n")

print("Saved: plots/sensitivity_table.tex")

# Boxplot comparing normal vs upperbody (already exists in earlier code)
# We'll create a new version with all songs in subplots

def plot_sensitivity_boxplot():
    """Create boxplot comparing normal vs upperbody for all songs."""
    
    df = merged_data_with_jds.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'].isin({'normal', 'upperbody'})].copy()
    
    # Define song order
    song_order = ['Old_Town_Road', 'Heart_Of_Glass', 'Unstoppable', 'Padam_Padam', 'Pink_Venom']
    songs = [s for s in song_order if s in df['song'].values]
    
    for jds_col, jds_name in [('jds_hand', 'Hand'), ('jds_arm', 'Arm')]:
        fig, axes = plt.subplots(1, len(songs), figsize=(3*len(songs), 4), sharey=True)
        if len(songs) == 1:
            axes = [axes]
        
        for idx, (song, ax) in enumerate(zip(songs, axes)):
            song_df = df[df['song'] == song]
            song_df = song_df[song_df[jds_col].notna()]
            
            normal_data = song_df[song_df['run_type'] == 'normal']
            upperbody_data = song_df[song_df['run_type'] == 'upperbody']
            
            # Box plot without individual points
            bp = ax.boxplot(
                [normal_data[jds_col].values, upperbody_data[jds_col].values],
                labels=['Normal', 'Upper\nbody'],
                widths=0.5,
                patch_artist=True,
                showfliers=False,
                medianprops=dict(color='black', linewidth=2),
                boxprops=dict(facecolor='lightblue', alpha=0.7, edgecolor='black', linewidth=1.5),
                whiskerprops=dict(color='black', linewidth=1.5),
                capprops=dict(color='black', linewidth=1.5)
            )
            
            # Title with multiline format
            title = format_song_with_level(song, multiline=True)
            ax.set_title(title, fontsize=7, fontweight='bold')
            ax.grid(True, axis='y', linestyle='--', alpha=0.3)
            ax.tick_params(axis='x', labelsize=7)
            
            if idx == 0:
                ax.set_ylabel(f'JDS Score ({jds_name})', fontsize=9, fontweight='bold')
        
        fig.suptitle(f'Sensitivity: Normal vs Upperbody - {jds_name} JDS',
                    fontsize=10, fontweight='bold')
        
        plt.tight_layout()
        filename = f'plots/sensitivity_boxplot_{jds_name.lower()}.png'
        plt.savefig(filename, dpi=150, bbox_inches='tight')
        plt.close()
        print(f"Saved: {filename}")

plot_sensitivity_boxplot()

# Create grouped bar plot of Cohen's d
if len(sensitivity_df) > 0 and 'Effect_Size' in sensitivity_df.columns:
    fig, ax = plt.subplots(figsize=(8, 5))
    
    # Define song order
    song_order = ['Old Town Road (Lvl 1)', 'Heart Of Glass (Lvl 2)', 'Unstoppable (Lvl 2)', 
                  'Padam Padam (Lvl 3)', 'Pink Venom (Lvl 4)']
    songs = [s for s in song_order if s in sensitivity_df['Song'].values]
    x = np.arange(len(songs))
    width = 0.35
    
    hand_effect = []
    arm_effect = []
    
    for song in songs:
        hand_row = sensitivity_df[(sensitivity_df['Song'] == song) & (sensitivity_df['JDS_Type'] == 'Hand')]
        arm_row = sensitivity_df[(sensitivity_df['Song'] == song) & (sensitivity_df['JDS_Type'] == 'Arm')]
        
        hand_effect.append(hand_row['Effect_Size'].values[0] if len(hand_row) > 0 and pd.notna(hand_row['Effect_Size'].values[0]) else 0)
        arm_effect.append(arm_row['Effect_Size'].values[0] if len(arm_row) > 0 and pd.notna(arm_row['Effect_Size'].values[0]) else 0)
    
    ax.bar(x - width/2, hand_effect, width, label='Hand JDS',
          alpha=0.8, color='skyblue', edgecolor='black')
    ax.bar(x + width/2, arm_effect, width, label='Arm JDS',
          alpha=0.8, color='salmon', edgecolor='black')
    
    # Reference lines for effect size interpretation
    ax.axhline(y=0.2, color='gray', linestyle=':', linewidth=1, alpha=0.5, label='Small (0.2)')
    ax.axhline(y=0.5, color='orange', linestyle=':', linewidth=1, alpha=0.5, label='Medium (0.5)')
    ax.axhline(y=0.8, color='green', linestyle=':', linewidth=1, alpha=0.5, label='Large (0.8)')
    
    ax.set_xlabel('Song', fontsize=10, fontweight='bold')
    ax.set_ylabel("Cohen's d", fontsize=10, fontweight='bold')
    ax.set_title("Sensitivity: Effect Size (Normal - Upperbody)", fontsize=11, fontweight='bold')
    ax.set_xticks(x)
    # Create multiline labels with smaller font
    song_labels = [s.replace(' (Lvl ', '\n(Lvl ') for s in songs]
    ax.set_xticklabels(song_labels, fontsize=7, ha='center')
    ax.legend(fontsize=8, loc='upper right')
    ax.grid(axis='y', alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('plots/sensitivity_effectsize.png', dpi=150, bbox_inches='tight')
    plt.close()
    print("Saved: plots/sensitivity_effectsize.png")


# ────────────────────────────────────────────────────────────────────────────
# 4. BIAS ANALYSIS (CVPR Publication-Ready)
# ────────────────────────────────────────────────────────────────────────────
print("\n" + "-"*80)
print("4. BIAS ANALYSIS")
print("-"*80)

def calculate_bias():
    """Test potential bias between Hand and Arm JDS."""
    
    # Filter to normal runs only
    df = merged_data_with_jds.copy()
    df['run_type'] = df['condition'].str.split('_').str[0]
    df = df[df['run_type'] == 'normal'].copy()
    df = df[df['jds_hand'].notna() & df['jds_arm'].notna()]
    
    bias_results = []
    
    for song in sorted(df['song'].unique()):
        song_df = df[df['song'] == song]
        
        if len(song_df) < 2:
            continue
        
        hand_scores = song_df['jds_hand'].values
        arm_scores = song_df['jds_arm'].values
        
        mean_hand = np.mean(hand_scores)
        mean_arm = np.mean(arm_scores)
        delta = mean_hand - mean_arm
        
        # Paired correlation
        r, _ = pearsonr(hand_scores, arm_scores)
        
        # Paired t-test
        _, p = ttest_rel(hand_scores, arm_scores)
        
        bias_results.append({
            'Song': format_song_with_level(song),
            'Mean_Hand': mean_hand,
            'Mean_Arm': mean_arm,
            'Δ': delta,
            'r': r,
            'p': p
        })
    
    return pd.DataFrame(bias_results)

# Calculate bias
bias_df = calculate_bias()

# Sort by song order
song_order = ['Old Town Road (Lvl 1)', 'Heart Of Glass (Lvl 2)', 'Unstoppable (Lvl 2)', 
              'Padam Padam (Lvl 3)', 'Pink Venom (Lvl 4)']
bias_df['song_order'] = bias_df['Song'].map({s: i for i, s in enumerate(song_order)})
bias_df = bias_df.sort_values('song_order').drop('song_order', axis=1)

print("\nBias Results:")
print(bias_df.to_string(index=False))

# Save bias table for supplementary material
bias_df.to_csv('plots/bias_hand_arm_table.csv', index=False)
print("\nSaved: plots/bias_hand_arm_table.csv")

# Save as LaTeX with improved formatting
bias_df_latex = bias_df.copy()

# Convert to thousands and calculate percentage bias
bias_df_latex['Hand_k'] = bias_df_latex['Mean_Hand'] / 1000
bias_df_latex['Arm_k'] = bias_df_latex['Mean_Arm'] / 1000
bias_df_latex['Delta_pct'] = (bias_df_latex['Δ'] / bias_df_latex['Mean_Hand']) * 100

# Calculate TOTAL statistics across all data points (not per-song averages)
# Get all hand and arm scores from the full dataset
df_total = merged_data_with_jds.copy()
df_total['run_type'] = df_total['condition'].str.split('_').str[0]
df_total = df_total[df_total['run_type'] == 'normal'].copy()
df_total = df_total[df_total['jds_hand'].notna() & df_total['jds_arm'].notna()]

all_hand_scores = df_total['jds_hand'].values
all_arm_scores = df_total['jds_arm'].values

# Total mean values
total_mean_hand = np.mean(all_hand_scores) / 1000  # in thousands
total_mean_arm = np.mean(all_arm_scores) / 1000    # in thousands

# Total correlation and p-value across all songs
total_r, total_p = pearsonr(all_hand_scores, all_arm_scores)

# Total percentage bias: calculate directly from total means
total_delta = total_mean_hand - total_mean_arm  # in thousands
total_delta_pct = (total_delta / total_mean_hand) * 100  # percentage relative to hand

# Build custom LaTeX table manually
with open('plots/bias_hand_arm_table.tex', 'w') as f:
    f.write("\\begin{table}[t]\n")
    f.write("\\caption{Comparison of hand- and arm-mounted JDS measurements across songs (n=30 trials per song). ")
    f.write("Values denote mean Just Dance Scores (×10³). ")
    f.write("$\\Delta$ represents percentage bias relative to hand-mounted scores.}\n")
    f.write("\\label{tab:bias}\n")
    f.write("\\centering\n")
    f.write("\\resizebox{\\columnwidth}{!}{\n")
    f.write("\\begin{tabular}{l|cc|c|cc}\n")
    f.write("\\toprule\n")
    f.write(" & \\multicolumn{2}{c|}{\\textbf{Mean JDS (×10³)}} & \\textbf{Bias} & \\multicolumn{2}{c}{\\textbf{Correlation}} \\\\\n")
    f.write("\\cmidrule(lr){2-3} \\cmidrule(lr){5-6}\n")
    f.write("\\textbf{Song} & Hand & Arm & $\\Delta$ (\\%) & r & p \\\\\n")
    f.write("\\midrule\n")
    
    # Write data rows
    for _, row in bias_df_latex.iterrows():
        song = row['Song']
        hand = row['Hand_k']
        arm = row['Arm_k']
        delta_pct = row['Delta_pct']
        r_val = row['r']
        p_val = row['p']
        
        # Format p-value: use proper LaTeX < symbol
        if p_val < 0.01:
            p_str = "$<$.01"
        else:
            p_str = f"{p_val:.2f}"
        
        f.write(f"{song} & {hand:.1f} & {arm:.1f} & {delta_pct:+.1f} & {r_val:.2f} & {p_str} \\\\\n")
    
    # Write total summary row
    f.write("\\midrule\n")
    # Format total p-value
    if total_p < 0.01:
        total_p_str = "$<$.01"
    else:
        total_p_str = f"{total_p:.2f}"
    
    f.write(f"\\textbf{{Total}} & \\textbf{{{total_mean_hand:.1f}}} & \\textbf{{{total_mean_arm:.1f}}} & \\textbf{{{total_delta_pct:+.1f}}} & \\textbf{{{total_r:.2f}}} & \\textbf{{{total_p_str}}} \\\\\n")
    f.write("\\bottomrule\n")
    f.write("\\end{tabular}}\n")
    f.write("\\end{table}\n")

print("Saved: plots/bias_hand_arm_table.tex (for appendix)")
# ──────────────────────────────────────────────────────────────────────────
# PLOT 1: Compact scatter plot for CVPR single column
# ──────────────────────────────────────────────────────────────────────────
df_bias_plot = merged_data_with_jds.copy()
df_bias_plot['run_type'] = df_bias_plot['condition'].str.split('_').str[0]
df_bias_plot = df_bias_plot[df_bias_plot['run_type'] == 'normal']
df_bias_plot = df_bias_plot[df_bias_plot['jds_hand'].notna() & df_bias_plot['jds_arm'].notna()]

if len(df_bias_plot) > 0:
    fig, ax = plt.subplots(figsize=(3.4, 3.4))

    # Define consistent colors per song
    song_colors_bias = {
        'Old_Town_Road': '#ff7f0e',
        'Heart_Of_Glass': '#1f77b4',
        'Unstoppable': '#9467bd',
        'Padam_Padam': '#2ca02c',
        'Pink_Venom': '#d62728',
    }

    # Plot each song
    song_order_raw = ['Old_Town_Road', 'Heart_Of_Glass', 'Unstoppable', 'Padam_Padam', 'Pink_Venom']
    for song in song_order_raw:
        if song in df_bias_plot['song'].values:
            song_data = df_bias_plot[df_bias_plot['song'] == song]
            ax.scatter(
                song_data['jds_hand'],
                song_data['jds_arm'],
                s=28, alpha=0.7, color=song_colors_bias.get(song, '#7f7f7f'),
                edgecolors='black', linewidth=0.4, label=format_song_with_level(song)
            )

    # Regression line and reference y=x line
    hand_vals = df_bias_plot['jds_hand'].values
    arm_vals = df_bias_plot['jds_arm'].values
    r_overall, p_overall = pearsonr(hand_vals, arm_vals)
    m, b = np.polyfit(hand_vals, arm_vals, 1)
    xs = np.linspace(hand_vals.min(), hand_vals.max(), 100)
    ax.plot(xs, m * xs + b, linestyle='--', color='black', linewidth=1.4,
            alpha=0.8, label=f'$r={r_overall:.2f}$, $p={p_overall:.3f}$')

    # Set equal axis scaling and rounded bounds
    combined_min = min(df_bias_plot['jds_hand'].min(), df_bias_plot['jds_arm'].min())
    combined_max = max(df_bias_plot['jds_hand'].max(), df_bias_plot['jds_arm'].max())
    combined_min = np.floor(combined_min / 500) * 500
    combined_max = np.ceil(combined_max / 500) * 500
    ax.set_xlim(combined_min, combined_max)
    ax.set_ylim(combined_min, combined_max)
    ax.set_aspect('equal', adjustable='box')

    # Dotted y=x reference line
    ax.plot([combined_min, combined_max], [combined_min, combined_max],
            linestyle=':', color='gray', linewidth=1.2, alpha=0.8, label='y=x')

    # Ticks and formatting
    ticks = np.arange(combined_min, combined_max + 1, 2000)
    ax.set_xticks(ticks)
    ax.set_yticks(ticks)
    ax.xaxis.set_major_formatter(lambda x, pos: f"{x/1000:.0f}k")
    ax.yaxis.set_major_formatter(lambda y, pos: f"{y/1000:.0f}k")

    # Labels and title
    ax.set_xlabel('Hand JDS Score', fontsize=9, fontweight='bold')
    ax.set_ylabel('Arm JDS Score', fontsize=9, fontweight='bold')
    ax.set_title('Hand vs Arm JDS', fontsize=10, fontweight='bold')

    # Legend and grid
    ax.legend(fontsize=6.2, loc='upper left', framealpha=0.95, bbox_to_anchor=(0.02, 0.98))
    ax.grid(True, linestyle='--', alpha=0.3)

    # Tight layout for CVPR single-column fit
    plt.tight_layout(pad=0.2)
    plt.savefig('plots/bias_hand_vs_arm_cvpr.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("Saved: plots/bias_hand_vs_arm_cvpr.png")

# ──────────────────────────────────────────────────────────────────────────
# PLOT 2: Mean bias (Δ = Hand - Arm) per song as compact bar plot
# ──────────────────────────────────────────────────────────────────────────
if len(bias_df) > 0:
    fig, ax = plt.subplots(figsize=(3.2, 2.4))
    
    # Prepare data for seaborn barplot
    plot_data = bias_df.copy()
    
    # Create barplot
    sns.barplot(
        data=plot_data,
        x='Song',
        y='Δ',
        color='steelblue',
        alpha=0.8,
        edgecolor='black',
        linewidth=1.2,
        ax=ax
    )
    
    # Add horizontal zero line
    ax.axhline(0, linestyle='--', color='gray', linewidth=1, alpha=0.7)
    
    # Labels and formatting
    ax.set_xlabel('Song', fontsize=9, fontweight='bold')
    ax.set_ylabel('$\\Delta$ (Hand - Arm)', fontsize=9, fontweight='bold')
    ax.set_title('Mean Bias per Song', fontsize=10, fontweight='bold')
    
    # Rotate x-axis labels for readability
    ax.set_xticklabels(ax.get_xticklabels(), rotation=40, ha='right', fontsize=8)
    ax.tick_params(axis='y', labelsize=8)
    ax.grid(axis='y', linestyle='--', alpha=0.3)
    
    plt.tight_layout(pad=0.3)
    plt.savefig('plots/bias_delta_bar.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("Saved: plots/bias_delta_bar.png")

# ──────────────────────────────────────────────────────────────────────────
# Summary statistics for bias analysis
# ──────────────────────────────────────────────────────────────────────────
print("\n--- Bias Analysis Summary ---")
print(f"Overall Hand-Arm correlation: r={r_overall:.3f}, p={p_overall:.4f}")

mean_delta = bias_df['Δ'].mean()
mean_abs_delta = bias_df['Δ'].abs().mean()
print(f"Mean bias (Δ = Hand - Arm): {mean_delta:.2f}")
print(f"Mean absolute bias |Δ|: {mean_abs_delta:.2f}")

if mean_delta > 0:
    print("→ Hand JDS tends to score HIGHER than Arm JDS on average.")
elif mean_delta < 0:
    print("→ Arm JDS tends to score HIGHER than Hand JDS on average.")
else:
    print("→ No systematic bias between Hand and Arm JDS.")

# Count songs with positive vs negative bias
positive_bias = (bias_df['Δ'] > 0).sum()
negative_bias = (bias_df['Δ'] < 0).sum()
print(f"Songs with Hand > Arm: {positive_bias}/{len(bias_df)}")
print(f"Songs with Arm > Hand: {negative_bias}/{len(bias_df)}")


# ────────────────────────────────────────────────────────────────────────────
# 5. SUMMARY
# ────────────────────────────────────────────────────────────────────────────
print("\n" + "-"*80)
print("5. OVERALL SUMMARY")
print("-"*80)

def create_overall_summary():
    """Create concise summary table with key metrics."""
    
    summary_data = []
    
    # Mean ICC(3,1)
    if len(reliability_df) > 0 and 'ICC(3,1)' in reliability_df.columns:
        mean_icc = reliability_df['ICC(3,1)'].mean()
    else:
        mean_icc = np.nan
    
    # Mean |r| from validity
    if len(validity_df) > 0:
        mean_abs_r = validity_df['r'].abs().mean()
    else:
        mean_abs_r = np.nan
    
    # Mean CV from reliability
    if len(reliability_df) > 0 and 'CV(%)' in reliability_df.columns:
        mean_cv = reliability_df['CV(%)'].mean()
    else:
        mean_cv = np.nan
    
    # Mean Cohen's d from sensitivity
    if len(sensitivity_df) > 0 and 'Effect_Size' in sensitivity_df.columns:
        mean_effect_size = sensitivity_df['Effect_Size'].mean()
    else:
        mean_effect_size = np.nan
    
    summary_data.append({
        'Metric': 'Overall',
        'Mean_ICC(3,1)': mean_icc,
        'Mean_|r|': mean_abs_r,
        'Mean_CV(%)': mean_cv,
        'Mean_Effect_Size': mean_effect_size
    })
    
    return pd.DataFrame(summary_data)

overall_summary_df = create_overall_summary()
print("\nOverall Summary:")
print(overall_summary_df.to_string(index=False))

# Save overall summary
overall_summary_df.to_csv('plots/overall_summary.csv', index=False)
print("\nSaved: plots/overall_summary.csv")

# Print textual summary
print("\n" + "="*80)
print("TEXTUAL SUMMARY FOR PAPER")
print("="*80)

mean_icc = overall_summary_df['Mean_ICC(3,1)'].values[0]
mean_r = overall_summary_df['Mean_|r|'].values[0]
mean_effect = overall_summary_df['Mean_Effect_Size'].values[0]

# Interpret ICC
if pd.notna(mean_icc):
    if mean_icc >= 0.9:
        icc_quality = "excellent"
    elif mean_icc >= 0.75:
        icc_quality = "good"
    elif mean_icc >= 0.5:
        icc_quality = "moderate"
    else:
        icc_quality = "poor"
else:
    icc_quality = "unknown"
    mean_icc = 0

# Interpret correlation strength
if pd.notna(mean_r):
    if mean_r >= 0.7:
        corr_strength = "strong"
    elif mean_r >= 0.5:
        corr_strength = "moderate"
    elif mean_r >= 0.3:
        corr_strength = "weak"
    else:
        corr_strength = "very weak"
else:
    corr_strength = "unknown"
    mean_r = 0

# Interpret effect size
if pd.notna(mean_effect):
    if mean_effect >= 0.8:
        effect_interp = "large"
    elif mean_effect >= 0.5:
        effect_interp = "medium"
    elif mean_effect >= 0.2:
        effect_interp = "small"
    else:
        effect_interp = "negligible"
else:
    effect_interp = "unknown"
    mean_effect = 0

summary_text = f"""
JDS demonstrates {icc_quality} test-retest reliability (ICC={mean_icc:.2f}), 
{corr_strength} correlation with established motion metrics (mean |r|≈{mean_r:.2f}),
and {effect_interp} sensitivity to degraded motions (Cohen's d≈{mean_effect:.2f}).
"""

print(summary_text)

print("\n" + "="*80)
print("PAPER RESULTS GENERATION COMPLETE")
print("="*80)
print("\nAll tables and figures saved to plots/ directory:")
print("  - reliability_table.csv / .tex")
print("  - reliability_icc_barplot.png")
print("  - validity_correlation_table.csv / .tex")
print("  - validity_heatmap_hand.png / validity_heatmap_arm.png")
print("  - validity_summary_barplot.png")
print("  - sensitivity_table.csv / .tex")
print("  - sensitivity_boxplot_hand.png / sensitivity_boxplot_arm.png")
print("  - sensitivity_effectsize.png")
print("  - bias_hand_arm_table.csv / .tex")
print("  - bias_hand_vs_arm_scatter.png")
print("  - overall_summary.csv")
print("="*80)
